### ISSUE TITLE
The Info.plist key 'BGTaskSchedulerPermittedIdentifiers' must contain a list of identifiers used to submit and handle tasks when 'UIBackgroundModes' has a value of 'processing'.

### ISSUE THREAD

**Issue by winsonet** [vrtdev/flutter_workmanager#105]
Sorry, it's me again!  😅

When I try to submit the app to app store, I just get below error:

```
The Info.plist key 'BGTaskSchedulerPermittedIdentifiers' must contain a list of identifiers used to submit and handle tasks when 'UIBackgroundModes' has a value of 'processing'.
```

![image](https://user-images.githubusercontent.com/1869995/67216965-a1c64080-f456-11e9-8d87-ee345dea3130.png)

and I did the research with google and find [this article](https://developer.apple.com/documentation/backgroundtasks/bgtaskscheduler) for handle this issue, but I don't understand how to set the array values

in that article said:

> Add a new item to the list and choose “Permitted background task scheduler identifiers”, which corresponds to the BGTaskSchedulerPermittedIdentifiers array.
> 
> Add the string for each authorized task identifier as a separate item in the array.

it that mean set this with my app's id? or the workmanager's package id?

thanks!

**Comment by Kymer** [comment]
Please refer to [Enabling Background Fetch](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md#enabling-background-fetch) section in our iOS setup readme. It seems like you enabled the wrong background mode in the Capabilities tab. You should select _Background fetch_ not _Background processing_:

![Screenshot of different background modes in Xcode](https://user-images.githubusercontent.com/9093854/67270565-35305d80-f4b9-11e9-8642-dfc6fc100c2f.png)

**Comment by kshivam117** [comment]
> Please refer to the [Enabling Background Fetch](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md#enabling-background-fetch) section in our iOS readme. It seems like you enabled the wrong background mode in the Capabilities tab. You should select _Background fetch_ not _Background processing_:
> 
> ![Screenshot of different background modes in Xcode](https://user-images.githubusercontent.com/9093854/67270565-35305d80-f4b9-11e9-8642-dfc6fc100c2f.png)

THANKS, A LOT
SOLUTION WORKED, SAVED MY DAY

**Comment by elmagy16** [comment]
adding this at the end worked for me.


</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>io.flutter.embedded_views_preview</key>
	<true/>
</dict>
</plist>

**Comment by elmagy16** [comment]
adding this at the end worked for me.


</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>io.flutter.embedded_views_preview</key>
	<true/>
</dict>
</plist>

**Comment by MPJHorner** [comment]
Thank you 🙏🏼🙏🏼🙏🏼
