### ISSUE TITLE
question: is initial delay also should work for iOS? 

### ISSUE THREAD

**Issue by pro100svitlo** [vrtdev/flutter_workmanager#111]
Hi!
Is initial delay also should work for iOS?
If no, is there any way to setup it?

Thanks

**Comment by timrijckaert** [comment]
The `initialDelay` and other properties are specific to the Android side.
However we started working on a `v2` of this plugin which will bridge this functionality to iOS as well.

You can subscribe to issue #109 for future updates.

**Comment by pro100svitlo** [comment]
Thanks!
