### ISSUE TITLE
Is there any way to run fetch on ios only when app idle ?

### ISSUE THREAD

**Issue by pro100svitlo** [vrtdev/flutter_workmanager#113]
Is there any way to run fetch on ios only when app idle ?

Why I am asking?
When we run workmanager task, its running inside `compute`(or similar, if I get it right), so the memory not shared bettwen threads and we need to init all stuff again.
Alot of db libraries ([sqlite](https://flutter.dev/docs/cookbook/persistence/sqlite), [hive](https://pub.dev/packages/hive), etc) didn't support to open db instance twice, so if app is already run and we are trying to open db from another thread - its crashed.
So I am wondered, is there any way to run ios fetch when app on idle (cos I already do it for android)?

**Comment by timrijckaert** [comment]
This will be possible with a future version of this library.
We are currently in progress of making it.
You can follow up on it by subscribing to https://github.com/vrtdev/ios-workmanager/issues/1

As of now, unfortunately no.
