### ISSUE TITLE
Run at Specific Time

### ISSUE THREAD

**Issue by sumitgohil** [vrtdev/flutter_workmanager#115]
So I wanted to implement dynamic Notification. For example, check for today's holiday and then send a notification with all the holiday details for the day. I would want to send the notification at 8'o Clock in the morning. 

I was wondering if I could use workmanager to execute at a specific time and with the help of it, I can create a notification in the background. 

Please, also suggest me if there is a better way of doing it.

**Comment by timrijckaert** [comment]
Nope,

The WorkManager is intended to be used with **non** time critical background tasks.  
I suggest you take a look at [this great video](https://www.youtube.com/watch?v=pe_yqM16hPQ) about when to use WorkManager and when not.

At 2:08 it specifically tells you to use `AlarmManager` API to trigger at an exact time.

**Comment by JonasJW** [comment]
@sumitgohil did you find a solution for this?

**Comment by sumitgohil** [comment]
> @sumitgohil did you find a solution for this?


Hi, check out this package https://pub.dev/packages/schedule_controller

I guess this could be useful, though I've not given a try yet.
