### ISSUE TITLE
Not able to execute dart code when app is not opened or when app is closed/killed?

### ISSUE THREAD

**Issue by anil-sookshum** [vrtdev/flutter_workmanager#116]
Is it possible to execute the dart code/function when the app is not opened/closed? Just line the **android_alarm_manager** plugin do for android. While it is working fine when app is in foreground or background.

**Comment by timrijckaert** [comment]
I'm afraid I don't understand your question.
Yes the code runs when the app is closed/killed.

Could you elaborate on your question?

**Comment by anil-sookshum** [comment]
For me, the code is executing when the app is in the foreground or in the background but not executing when the app is killed /closed. I tried by running the provided example but still, I have the same results.

**Comment by anil-sookshum** [comment]
I am executing an async function for fetching data from API and showing notification based on that. But not working when the app is killed/closed.

**Comment by timrijckaert** [comment]
I just tried the example and it works.
Can you assert that you did the following steps in the example app:
- Start the Flutter background service
- Register Delayed OneOff Task
- Kill the app
- Wait a debug notification should be shown

![untitled](https://user-images.githubusercontent.com/6739443/68100711-b7614e80-fec9-11e9-8578-ccefa8e54906.gif)

**Comment by anil-sookshum** [comment]
That's exactly what I am doing. I tried with two test case one when the app is running and another when the app is killed/closed. The first case is working only, take a look : 
![20191104_113618](https://user-images.githubusercontent.com/44391555/68102191-8c8def00-fef7-11e9-875f-c4720226dc49.gif)

**Comment by anil-sookshum** [comment]
En edition I have test with various devices i.e. Redmi note 4, Note 5 Pro, OnePlus 5, etc. Is there is anything extra needs to be configured with the example provided or can you provide me a snipped of working code?

**Comment by timrijckaert** [comment]
The sample is working code.

Can you uninstall the sample app and install it again and follow these exact steps:
- Start the Flutter background service
- Register Delayed OneOff Task
- Kill the app
- Wait a debug notification should be shown

Can you run in an emulator?

**Comment by anil-sookshum** [comment]
@timrijckaert  looks like working fine on an emulator. But the problem still remains with the physical devices.

**Comment by timrijckaert** [comment]
I don't have access to the device you named.
However we have a OnePlus 3 and OnePlus 6 and it works fine here.

Even if it didn't I'm afraid this is not due to this lib

**Comment by cormalenv** [comment]
I appreciate this is old but for others.... after facing the same issue I read that some devices with custom Android ROMs (most notably cheaper Chinese devices) indiscriminately kill off process as they see fit. I was facing the same problem on a Xiaomi 6. The `workmanager example` runs fine until the app is closed where upon a period task is then killed off. On a Samsung s8 however it continues fine after the app is killed.

**Comment by flutteresbolivia** [comment]
I have the same problem.

**Comment by Myzel394** [comment]
The example code does not work anymore (Running on an emulator with Android 12) @timrijckaert is there any solution available?

**Comment by timrijckaert** [comment]
I’m sorry I’m no longer maintaining nor active in Flutter
