### ISSUE TITLE
🐞[iOS periodic background task not executed]

### ISSUE THREAD

**Issue by marcin-adamczewski** [vrtdev/flutter_workmanager#117]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Workmanager version  |       0.1.4
| Xcode version        |    11.2
| Swift version        |     from sample app
| iOS deployment target |  from sample app

**Describe the error**
Hi,
I can't make a periodic background task to execute on iOS. I've tried your sample App, went through ios_setup_readme, added `UIApplication.shared.setMinimumBackgroundFetchInterval(TimeInterval(60*3))`.
I ran the app and then clicked `initialize` button. Then closed the app using the home button.
Nothing happens, I cannot see debug notification. I was waiting for a couple of hours. However, using simulator Debug->Background Fetch works fine.
Any help? Can you run background task using real iOS device without background fetch debug option?
I'm using iOS 13.2 on Iphone10s

**Output of `flutter doctor -v`**

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A603, locale en-PL)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2019.2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by Kymer** [comment]
> Nothing happens, I cannot see debug notification. I was waiting for a couple of hours.

iOS tries to be smart about scheduling your app for background fetches. It uses a complicated set of heuristics to determine *which app* should be allowed to run *when*, taking into account the usage pattern of the user and the state of the phone (battery level, cellular/WiFi connectivity level, etc etc). It looks at *how often* you open the app and *when* (time of day), how long you use the app, whether or not the app consumes a lot of data / battery power etc before 'allowing' the it to run in the background.


The scheduling heuristic of iOS is of course a complete black box. So there is no way of knowing what is going on *exactly*, as a developer. But simply waiting for a few hours will not work. You'll need to actually launch the app during the day and use it like a 'real' user would, so don't launch and close immediately. From our testing it takes at least a day before iOS starts 'regularly' scheduling your app to run in the background.

**Comment by timrijckaert** [comment]
Since this is so hard to _debug_ we made it simpler for you, if you have set the `isInDebugMode: true` you'll receive a debug notification once the task has run.
See full explanation in the [iOS Readme]((https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
