### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by erolasan** [vrtdev/flutter_workmanager#118]
** BUILD FAILED **
Xcode's output:
↳
    === BUILD TARGET gRPC-Core OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/erolasan/flutter/.pub-cache/hosted/pub.dartlang.org/workmanager-0.1.4/ios/Classes/WorkmanagerPlugin.m:2:9: fatal error: 'workmanager/workmanager-Swift.h' file not found
    #import <workmanager/workmanager-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

**Comment by Kymer** [comment]
Please open a new ticket and use the bug report template. Make sure to fill in the requested info (Xcode version, Swift version etc). We need more detailed info about your setup in order to investigate further
