### ISSUE TITLE
Conflict with speech_recognition plugin

### ISSUE THREAD

**Issue by gustavobilert** [vrtdev/flutter_workmanager#120]
Thanks for making this plugin!
But I am not being able to use it because it is conflicting with another plugin: speech_recognition
Steps to reproduce:
- Take the workmanager example app
- Add the dependency: speech_recognition: "^0.3.0"
- Run any task
- The app crashes

**Comment by timrijckaert** [comment]
The problem is not this library.
Open a ticket on the `speech_recognition` lib.

The offending line is:

https://github.com/rxlabz/speech_recognition/blob/master/android/src/main/java/bz/rxla/flutter/speechrecognition/SpeechRecognitionPlugin.java#L37
