### ISSUE TITLE
[Android] How to specify that task failed 

### ISSUE THREAD

**Issue by fvisticot** [vrtdev/flutter_workmanager#121]
The following task should success / fail depending on the value of `res`.

Even if I force the `res` to `false` I get always the result:
```
I/WM-WorkerWrapper(15034): Worker result SUCCESS for Work [ id=0e75bcd9-3b05-4bd1-9ed5-22feafab4975, tags={ be.tramckrijte.workmanager.BackgroundWorker } 
```

What do I need to return to have the Worker result to FAIL and try to replay the task again (policy)

```dart
void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) async {
    bool res = await BeaconEventsStoreSynchroManager.instance.synchronize();
    return Future.value(res); // forced to false for test
  });
}
```

**Comment by timrijckaert** [comment]
Nice catch.
Wondered why nobody ever complained about this.

I'm preparing a hot fix.

**Comment by timrijckaert** [comment]
Version `0.1.5` is now available on pub.

Thanks again.
