### ISSUE TITLE
Exception when register a periodic task

### ISSUE THREAD

**Issue by DjarjoMaster** [vrtdev/flutter_workmanager#123]
I faced following issue when registering a periodic task

`E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 2649): Failed to handle method call
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 2649): java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 2649): 	at androidx.work.impl.WorkManagerImpl.getInstance(WorkManagerImpl.java:140)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 2649): 	at androidx.work.WorkManager.getInstance(WorkManager.java:180)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 2649): 	at be.tramckrijte.workmanager.WorkmanagerCallHandlerKt.workManager(WorkmanagerCallHandler.kt:12)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 2649): 	at be.tramckrijte.workmanager.WorkmanagerCallHandlerKt.access$workManager(WorkmanagerCallHandler.kt:1)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 2649): 	at be.tramckrijte.workmanager.WM.enqueuePeriodicTask(WorkmanagerCallHandler.kt:169)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 2649): 	at be.tramckrijte.workmanager.RegisterTaskHandler.enqueuePeriodicTask(WorkmanagerCallHandler.kt:64)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 2649): 	at be.tramckrijte.workmanager.RegisterTaskHandler.handle(WorkmanagerCallHandler.kt:58)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 2649): 	at be.tramckrijte.workmanager.WorkmanagerCallHandler.handle(WorkmanagerCallHandler.kt:23)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 2649): 	at be.tramckrijte.workmanager.WorkmanagerPlugin.onMethodCall(WorkmanagerPlugin.kt:27)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 2649): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 2649): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 2649): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 2649): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 2649): 	at android.os.MessageQueue.next(MessageQueue.java:143)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 2649): 	at android.os.Looper.loop(Looper.java:122)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 2649): 	at android.app.ActivityThread.main(ActivityThread.java:5421)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 2649): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 2649): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 2649): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 2649): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
W/MALI    ( 2649): glDrawArrays:714: [MALI] glDrawArrays takes more than 5ms here. Total elapse time(us): 10208
E/flutter ( 2649): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider., null)
E/flutter ( 2649): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 2649): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter ( 2649): <asynchronous suspension>
E/flutter ( 2649): #2      Workmanager.registerPeriodicTask (package:workmanager/src/workmanager.dart:157:32)
`

After searching I found this stackoverflow article [https://stackoverflow.com/questions/56729702/call-workmanagerimpl-getinstance-in-background-systemjob-systemjobservice-oncrea](url)

In case this is the reason for the exception, could you please upgrade to the new version (e.g. 2.2.0) of the work-runtime ?

**Comment by stefanJi** [comment]
@DjarjoMaster There are two ways to fix this issue. You can try.

1. Disable `On-Demand Initialization`:

remove as follow code from your android project manifest.xml:

```xml
<provider
    android:name="androidx.work.impl.WorkManagerInitializer"
    android:authorities="${applicationId}.workmanager-init"
    tools:node="remove" />
```
This will disable WorkManager's `On-Demand Initialization` feature.

---

2. Create a yourself Application class and make it implement `Configuration.Provider`. As follow:

```java
public class MApp extends FlutterApplication implements Configuration.Provider {
    @Override
    public void onCreate() {
        super.onCreate();
       //Must call super for Flutter framework's init
    }

    @NonNull
    @Override
    public Configuration getWorkManagerConfiguration() {
        return new Configuration.Builder().build();
    }
}
```

Modify manifest.xml as follow:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="io.github.stefanji.fluttergitlab">

    <application
        android:name=".MApp" 
    >
        <activity>...</activity>

        <provider
            android:name="androidx.work.impl.WorkManagerInitializer"
            android:authorities="${applicationId}.workmanager-init"
            tools:node="remove" />

    </application>
</manifest>
```

You also need add WorkManager's dependencies for compiler.

```
def work_version = "2.1.0"
implementation "androidx.work:work-runtime:$work_version"
```

This way will support WorkManager's `On-Demand Initialization` feature. For better performance, I suggest you use second way.

**Comment by DjarjoMaster** [comment]
@stefanJi Thanks a lot. The second way works perfect for me
