### ISSUE TITLE
[iOS] Build failure (UIImagePNGRepresentation)

### ISSUE THREAD

**Issue by fvisticot** [vrtdev/flutter_workmanager#125]
When compiling for iOS, I get the following errror

Flutter 1.9.1+hotfix.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68587a0916 (3 months ago) • 2019-09-13 19:46:58 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0
XCode: 11.2.1

Command CompileSwift failed with a nonzero exit code
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/workmanager-0.1.5/ios/Classes/ThumbnailGenerator.swift:85:36: error: 'pngData()' has been renamed to 'UIImagePNGRepresentation(_:)'
            guard let imageData = self.pngData() else {
                                       ^~~~~~~
                                       UIImagePNGRepresentation
    UIKit.UIImage:58:17: note: 'pngData()' was introduced in Swift 4.2
        public func pngData() -> Data?

**Comment by Kymer** [comment]
I am able to successfully run the sample app with Xcode 11.2.1. So please refer to my comments in issue #84 and report back. Basicly make sure your project is set to Swift 4.2 or higher and see if the error persists.

Sample app running from Xcode 11.2.1 👇 

![Sample app running in Xcode 11.2.1](https://user-images.githubusercontent.com/9093854/70518225-4c470f80-1b3a-11ea-990f-4c342e4cab2d.png)

**Comment by andreidiaconu** [comment]
I was getting the same error at build time. Turns out I was using Swift 4.0 and upgrading to 4.2 solved the problem for me (*Runner* -> *Build Settings* -> *Swift Language Version*).

**Comment by vanlooverenkoen** [comment]
That did not work for me.
In my podfile I had to add the following

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    ...
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '4.2'
    end
    ...
  end
end
```
