### ISSUE TITLE
Exception has occurred. PlatformException (PlatformException(unhandledMethod("registerPeriodicTask") error, Unhandled method registerPeriodicTask, null))

### ISSUE THREAD

**Issue by agreensh** [vrtdev/flutter_workmanager#127]
Only testing on iOS. I have enabled background mode and added the '    UIApplication.shared.setMinimumBackgroundFetchInterval(TimeInterval(60*15))' line, but the app doesn't get that far... Seems like the "registerPeriodicTask" method does not exist (same error for the "registerOneOffTask").

- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there
(this error for the example app from xcode)

2019-12-22 21:33:30.315521+0000 Runner[28113:10355326] flutter: Observatory listening on http://127.0.0.1:54548/P5blQ-nl9-c=/
2019-12-22 21:33:33.493145+0000 Runner[28113:10355312] [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(unhandledMethod("registerPeriodicTask") error, Unhandled method registerPeriodicTask, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |      0.1.5         |
| Xcode version        |       11.2.1        |
| Swift version        |        Swift 5       |
| iOS deployment target|         10.0      |

**Describe the error**
(from vscode)
Exception has occurred. PlatformException (PlatformException(unhandledMethod("registerPeriodicTask") error, Unhandled method registerPeriodicTask, null))

(from xcode)
2019-12-22 21:26:58.759891+0000 Runner[25923:10333526] flutter: Observatory listening on http://127.0.0.1:53713/szijLAxZLVs=/
2019-12-22 21:26:59.641932+0000 Runner[25923:10333513] [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(unhandledMethod("registerPeriodicTask") error, Unhandled method registerPeriodicTask, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)

Optionally provide the least amount of code that shows this behaviour. Ideally in the `sample` app.

const myTask = "testWorkManager";

void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) {
    switch (task) {
      case myTask:
        print("this method was called from native!");
        break;
      case Workmanager.iOSBackgroundTask:
        print("iOS background fetch delegate ran");
        break;
    }

    return Future.value(true);
  });
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  Workmanager.initialize(callbackDispatcher, isInDebugMode: true);
  Workmanager.registerPeriodicTask(
    "1",
    myTask,
  );
  runApp(MyApp());
}
***NOTE:  MyApp is the default Flutter counter app ***

**Output of `flutter doctor -v`**
[✓] Flutter (Channel dev, v1.13.5, on Mac OS X 10.15.2 19C57, locale en-GB)
    • Flutter version 1.13.5 at /Users/Andy/flutter
    • Framework revision 41a911099b (3 days ago), 2019-12-19 13:48:02 -0800
    • Engine revision 0f90e6546b
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 aa6709974d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/Andy/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/Andy/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B53
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (4 available)
    • iPhone 7   • E366941C-DEF7-4310-A703-3AA694FAF491 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
    • macOS      • macOS                                • darwin-x64     • Mac OS X 10.15.2 19C57
    • Chrome     • chrome                               • web-javascript • Google Chrome 79.0.3945.88
    • Web Server • web-server                           • web-javascript • Flutter Tools

• No issues found!

**Comment by timrijckaert** [comment]
registering Periodic Tasks is only available for Android as of now.  https://github.com/vrtdev/flutter_workmanager#customisation-android-only

**Comment by agreensh** [comment]
Please update the documentation to make this clear - the first example (outside of the Android customisation section) shows exactly what I did.
void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) {
    print("Native called background task: $backgroundTask"); //simpleTask will be emitted here.
    return Future.value(true);
  });
}

void main() {
  Workmanager.initialize(
    callbackDispatcher, // The top level function, aka callbackDispatcher
    isInDebugMode: true // If enabled it will post a notification whenever the task is running. Handy for debugging tasks
  );
  Workmanager.registerOneOffTask("1", "simpleTask");
  runApp(MyApp());
}

If you are implementing this for iOS only, you will NOT read the Android section and thus think (reasonably, given the way the documentation presents the info) that the example you give applies to both iOS and Android.

**Comment by timrijckaert** [comment]
Added an extra comment in the example. 👍

**Comment by agreensh** [comment]
Can I add a "Fix TFM" label?

**Comment by Kymer** [comment]
> Can I add a "Fix TFM" label?

Feel free to update the documentation as you see fit and open a PR 👍
