### ISSUE TITLE
cant use my invokeMethod in callbackDispatcher

### ISSUE THREAD

**Issue by mojanimator** [vrtdev/flutter_workmanager#135]
Hi 

I have a channel in my `MainActivity` that changes a background device, but when I try to use it in the `callbackDispatcher`, it throws missing plugin exception:  

> MissingPluginException(No implementation found for method getWallpaper on channel change_wallpaper)

This is my  code:

```dart
void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) async {
    switch (task) {
   
      case CHANGE_WALLPAPER:
        await const MethodChannel('change_wallpaper')
              .invokeMethod('getWallpaper', {"text":"sometext"});
     
        break;
    }
  
    return Future.value(true);
  });
}
```

Do note this is not a plugin; This code is in my Android code. 

How can i solve it? 

Thanks

**Comment by timrijckaert** [comment]
When the `callbackDispatcher` is called your plugins will be registered, but it won't register plugins which are registered inside a `MainActivity`.  
You could however try and move the code to register itself inside a custom `Application` class which is always going to be active when a background job starts running.  

Hope this helps, let me know

**Comment by mojanimator** [comment]
ok . thank for your reply sir. i tested your answer and put my code in application class. but i dont know what is first input in channel:
public class App extends FlutterApplication {
 methodChannel = new MethodChannel(flutterEngine.getDartExecutor(), CHANNEL);

what is replacement of flutterEngine.getDartExecutor() in FlutterApplication ?

**Comment by tirgil** [comment]
I have the same problem. I'm trying to use other plugins (such as flutter_local_notifications), but i can't figure it out.  It always say MissingPluginException, whatever i try. Did you find a solution for that?

**Comment by sinhpn92** [comment]
I have same issue too :((

**Comment by petermnt** [comment]
The example app uses an external plugin in the callback, so it should be supported. 

```dart
 Directory tempDir = await getTemporaryDirectory();
        String tempPath = tempDir.path;
        print(
            "You can access other plugins in the background, for example Directory.getTemporaryDirectory(): $tempPath");
```

**Comment by netofontess** [comment]
I have the same issue with Sqflite.
I init my database in 'main()' and when i try use a query inside background task, the Database object is null... So i receive the message '[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'query' was called on null.'
Can you make an example for sqflite?

Tk's!

**Comment by gfiury** [comment]
I been trying to use the `workmanager` with the `flutter_local_notifications` and couldn't make it work, because of the `MissingPluginException`.

Found this [repo](https://github.com/acctgen1/flutter-push-notification-without-firebase) with both plugin's working

**Comment by wonpyohong** [comment]
same problem. why did this issue closed?
