### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by MrFane** [vrtdev/flutter_workmanager#139]
Hi I'm facing with a serious issue, I tried to build my app in release mode but when i try to build it, it says this : 

--------------------------------------------------------------------------------------------------------------
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':shared_preferences:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\MrFane\.gradle\caches\transforms-2\files-2.1\a1e87f5443b1512d74d302dbaa8fc6ba\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationS
ettings not found.

     C:\Users\MrFane\.gradle\caches\transforms-2\files-2.1\a1e87f5443b1512d74d302dbaa8fc6ba\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not f
ound.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 53s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                     175.5s (!)
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin shared_preferences...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                   41.7s
√ Built build\app\outputs\repo.
Building plugin workmanager...
The plugin workmanager could not be built due to the issue above.
Running Gradle task 'assembleAarRelease'... 
--------------------------------------------------------------------------------------------------------------

OUTPUT OF "flutter doctor -v" : 

[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.592], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\flutter
    • Framework revision 27321ebbad (7 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\MrFane\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\MrFane\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • ANE LX1 • 89U4C18807007940 • android-arm64 • Android 9 (API 28)

• No issues found!
-------------------------------------------------------------------------------------------

If you could help me it would be very very great! Thanks!

**Comment by petermnt** [comment]
This does not look to be directly related to this plugin.
It looks like you might be missing the full AndroidX setup (Jetifier)
