### ISSUE TITLE
🐞[0.2.0] Async tasks can't be executed anymore

### ISSUE THREAD

**Issue by estevez-dev** [vrtdev/flutter_workmanager#142]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [ ] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |  0.2.0  |

**Describe the error**
I updated workmanager in [my app](https://github.com/estevez-dev/ha_client) from 0.1.5 to 0.2.0 and migrated to **Flutter Embedding v.2**. My background execution tasks is not working anymore because it's execution takes some time. I mean several seconds, not even minutes. You can reproduce the issue with this simple app:

```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:workmanager/workmanager.dart';

void main() => runApp(MyApp());

void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) async {
    print("Starting $task with ${inputData['duration']}ms timer...");
    Timer(Duration(milliseconds: inputData['duration']), () {
      print("$task with ${inputData['duration']}ms timer was finished.");
    });
    return Future.value(true);
  });
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  @override
  void initState() {
    Workmanager.initialize(
      callbackDispatcher,
      isInDebugMode: false,
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("Flutter WorkManager Example"),
        ),
        body: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: <Widget>[
              RaisedButton(
                  child: Text("OneOff with 100ms timer"),
                  onPressed: () {
                    Workmanager.registerOneOffTask(
                      "1",
                      "test1",
                      inputData: <String, dynamic>{
                        'duration': 100
                      },
                    );
                  }),
              SizedBox(height: 8),
              RaisedButton(
                  child: Text("OneOff with 5sec timer"),
                  onPressed: () {
                    Workmanager.registerOneOffTask(
                      "1",
                      "test2",
                      inputData: <String, dynamic>{
                        'duration': 5000
                      },
                    );
                  }),
              SizedBox(height: 8),
              RaisedButton(
                  child: Text("Periodic with 1ms timer"),
                  onPressed: () {
                    Workmanager.registerPeriodicTask(
                      "1",
                      "test3",
                      frequency: Duration(minutes: 15),
                      initialDelay: Duration(seconds: 2),
                      inputData: <String, dynamic>{
                        'duration': 1
                      },
                    );
                  }),
              SizedBox(height: 8),
              RaisedButton(
                  child: Text("Periodic with 3sec timer"),
                  onPressed: () {
                    Workmanager.registerPeriodicTask(
                      "1",
                      "test4",
                      frequency: Duration(minutes: 15),
                      initialDelay: Duration(seconds: 2),
                      inputData: <String, dynamic>{
                        'duration': 3000
                      },
                    );
                  }),
              SizedBox(height: 16),
              RaisedButton(
                  child: Text("Cancel all"),
                  onPressed: () async {
                    await Workmanager.cancelAll();
                    print('Canceled');
                  }),
            ],
          ),
        ),
      ),
    );
  }
}
```
The only timer that will be finished in this example is the one started with "Periodic with 1ms timer" button.

**Output of `flutter doctor -v`**
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.7 at /workspace/flutter
    • Framework revision 9f5ff2306b (3 weeks ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /workspace/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /workspace/android-sdk
    • Java binary at: /home/gitpod/.sdkman/candidates/java/current/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-b08)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Pixel 3 XL • 0.tcp.ngrok.io:13210 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

**Comment by osamabinishrat** [comment]
I am having the same problem. Async tasks are not executing in callbackDispatcher() function. 

Anyone please help.

**Comment by petermnt** [comment]
Hello @estevez-dev 

This behaviour is expected. You are not awaiting your Timer. The task is assumed complete when the callbacks gets to its return value.

Your example has the following:
```dart
void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) async {
    print("Starting $task with ${inputData['duration']}ms timer...");
    Timer(Duration(milliseconds: inputData['duration']), () {
      print("$task with ${inputData['duration']}ms timer was finished.");
    });
    return Future.value(true);
  });
}
```

When changing it to this, it does work as expected.
```dart
void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) async {
    print("Starting $task with ${inputData['duration']}ms timer...");

    await Future.delayed(Duration(milliseconds: inputData['duration']));
    print("$task with ${inputData['duration']}ms timer was finished.");
    return true;
  });
}
```

So make sure to await your long running task inside the `executeTask` callback

**Comment by estevez-dev** [comment]
So today I realized what I was doing wrong. Here is my callback:
```dart
void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) async {
    Completer completer = Completer();
    print("Starting $task with ${inputData['duration']}ms timer...");
    Timer(Duration(milliseconds: inputData['duration']), () {
      print("$task with ${inputData['duration']}ms timer was finished.");
      completer.complete(true);
    });
    return completer.future;
  });
}
```
It is almost the same but different ))) Today I noticed that `executeTask` is *async* and should use *await* instead of returning Future.

**Comment by estevez-dev** [comment]
Sorry, I suppose this can be closed ))

**Comment by MuhammedRefaat** [comment]
> So today I realized what I was doing wrong. Here is my callback:
> 
> ```dart
> void callbackDispatcher() {
>   Workmanager.executeTask((task, inputData) async {
>     Completer completer = Completer();
>     print("Starting $task with ${inputData['duration']}ms timer...");
>     Timer(Duration(milliseconds: inputData['duration']), () {
>       print("$task with ${inputData['duration']}ms timer was finished.");
>       completer.complete(true);
>     });
>     return completer.future;
>   });
> }
> ```
> 
> It is almost the same but different ))) Today I noticed that `executeTask` is _async_ and should use _await_ instead of returning Future.

I used this exact way but still can't get the tasks in future function to be done, always skips directly to the end of the callback without waiting any future function, used await and used future and used completer but no luck.

**Comment by SSVernekar** [comment]
void callbackDispatcher() async{

  Workmanager.executeTask((task, inputData) async {

print("responce : ${inputData['plants'].toList()}");



List<NotificationData> notifications = [NotificationData("1","a"),NotificationData("2","a")];



 for (var notificationData in inputData['plants'].toList()){

     notifications.add(NotificationData(
         notificationData["meterId"]!="null"?notificationData["meterId"]:0, notificationData["lastDayEnergy"]!="null"?notificationData["lastDayEnergy"]:0));
}



  showNotification(notifications);
   return true;
  });

**Comment by aadi-github** [comment]
> 



> In the following code if i remove for loop showNotification works otherwise not workmanager fails please help me anyone.
> 
> void callbackDispatcher() async{
> 
> Workmanager.executeTask((task, inputData) async {
> 
> print("responce : ${inputData['plants'].toList()}"); List notifications = [NotificationData("1","a"),NotificationData("2","a")];
> 
> ```
> for (var notificationData in inputData['plants'].toList()){
> 
>   notifications.add(NotificationData(
>   notificationData["meterId"]!="null"?notificationData["meterId"]:0, notificationData["lastDayEnergy"]!="null"? 
>   notificationData["lastDayEnergy"]:0));
> ```
> 
> }
> 
> showNotification(notifications); return true; });

I am also facing the same issue,
for loop does not getting executed, without it Notification works, here is the example code from Workmanager().executeTask(...);

        for (decDuration = 0; decDuration >= durationElapsed.inSeconds; decDuration++) {
          await Future.delayed(const Duration(seconds: 1)); //here awaiting for 1 sec but no luck
          AppConstants.logger('Testing.....$decDuration');
          AndroidNotificationDetails and = AndroidNotificationDetails(
            'parked_vehicle',
            'Vehicle Parking Time Remaining',
            channelDescription:
                'This Notification will notify the user that vehicle\'s time of booking for the parking is about to expire.',
            importance: Importance.max,
            priority: Priority.max,
            channelShowBadge: false,
            ticker: 'parked_vehicle',
            color: Colors.blue,
            onlyAlertOnce: true,
            showProgress: true,
            progress: decDuration,
            maxProgress: totalDuration.inSeconds,
            visibility: NotificationVisibility.public,
          );
          NotificationDetails platformSpecificDetails =
              NotificationDetails(android: and);

          await flutterLocalNotificationsPlugin.show(
            nID,
            '${booking.vehicleNumber} is parked at ${booking.lotName}',
            'Parking is about to end in -- ${AppConstants.formatDuration(Duration(seconds: decDuration))}',
            platformSpecificDetails,
          );
        }

Please let me know if we need to do something more for executing for loop, because without for loop  await Future.delayed works. I have checked delaying for 3 sec, 3 times.
