### ISSUE TITLE
🐞Can't call method inside iOSBackgroundTask

### ISSUE THREAD

**Issue by murilinhoPs** [vrtdev/flutter_workmanager#145]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [ ] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [ ] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |     0.2.1          |
| Xcode version        |       11.3.1        |
| Swift version        |        I don't know       |
| iOS deployment target|      10.0         |

**Describe the error**
I'm trying to call a method with BlocPattern from the AppModule inside iOSBackgroundTask, but the task return failed in the debug notification and in the console:'AppModule is not in the widget tree'. If I only call print('iOS task'), the workmanager return success in the notification. 
Can someone help me?

Here is my code: 

void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) async {
    switch (task) {
      case Workmanager.iOSBackgroundTask:
        print('IOS task');
        await _infos();
        break;
    }

    //Return true when the task executed successfully or not
    return Future.value(true);
  });
}

_infos()
{
   await AppModule.to.bloc<MyBloc>().blocMethod();
   print('works!');
}

**Comment by petermnt** [comment]
I looks like you're trying to access something from a Widget. This is not possible.
The background code cannot depend on widgets.

**Comment by murilinhoPs** [comment]
Ah okay, now I understand and make sense. Thanks for answer!
Closing the issue...
