### ISSUE TITLE
Cannot execute operation because FlutterJNI is not attached to native

### ISSUE THREAD

**Issue by SlimenTN** [vrtdev/flutter_workmanager#148]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |     ^0.2.0          |
| Xcode version        |               |
| Swift version        |               |
| iOS deployment target|               |

**Describe the error**
```
E/AndroidRuntime(12943): FATAL EXCEPTION: main
E/AndroidRuntime(12943): Process: com.operatingplans.opp, PID: 12943
E/AndroidRuntime(12943): java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
E/AndroidRuntime(12943): 	at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:227)
E/AndroidRuntime(12943): 	at io.flutter.embedding.engine.FlutterJNI.detachFromNativeAndReleaseResources(FlutterJNI.java:212)
E/AndroidRuntime(12943): 	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:282)
E/AndroidRuntime(12943): 	at be.tramckrijte.workmanager.BackgroundWorker$stopEngine$1.run(BackgroundWorker.kt:98)
E/AndroidRuntime(12943): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(12943): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(12943): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(12943): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(12943): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12943): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(12943): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(12943): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Output of `flutter doctor -v`**
[√] Flutter (Channel beta, v1.14.6, on Microsoft Windows [version 10.0.18363.657], locale fr-FR)
    • Flutter version 1.14.6 at G:\Programes\flutter
    • Framework revision fabeb2a16f (5 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Slimen\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: G:\Programes\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at G:\Programes\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] VS Code
    • VS Code at C:\Users\Slimen\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 5.1.1 (API 22) (emulator)

My code:
```javascript
void main(){
  WidgetsFlutterBinding.ensureInitialized();

  wm.Workmanager.initialize(
      callbackDispatcher, // The top level function, aka callbackDispatcher
      isInDebugMode: true // If enabled it will post a notification whenever the task is running. Handy for debugging tasks
  );
  print('init work manager');
  wm.Workmanager.registerOneOffTask(
    "1",
    "syncWithTheBackEnd", //This is the value that will be returned in the callbackDispatcher
//    initialDelay: Duration(seconds: 5),
    constraints: wm.Constraints(
      requiresCharging: true,
      networkType: wm.NetworkType.connected,
    ),
  );

  runApp(MyApp());
}

void callbackDispatcher() {
  print('callbackDispatcher');
  wm.Workmanager.executeTask((task, inputData) {
    Timer.periodic(Duration(seconds: 15), (Timer t) {
      print('message each 15 second');
    });
    print("Native called background task: pusher"); //simpleTask will be emitted here.
    return Future.value(true);
  });
}
```

**Comment by petermnt** [comment]
I see a few issues here:

* You need to `await` the `initialize` before using `registerOneOffTask`
* The Timer you use in your `execute` will not work. Execution will stop when the execute method finishes. If you need to do long-running tasks you need to await them. Plus it's not possible/advised to do an infinite task here.

There did seem to be an issue though where a `FlutterEngine` was sometimes destroyed more than once, causing this crash. I have solved this issue and released version 0.2.2
