### ISSUE TITLE
Missing implementation for a plugin

### ISSUE THREAD

**Issue by goranristic123** [vrtdev/flutter_workmanager#149]
**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |  ^0.2.0  |
| Xcode version        |  |
| Swift version        |  |
| iOS deployment target|               |

**Describe the error**
When workmanager runs in background I get following message
```
MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
```
I'm using v2 embedding so it should automatically register plugin in background?
I know this may not and probably isn't workmanagers issue, but none of the solutions I found are working. Any ideas?

**Output of `flutter doctor -v`**
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.2 19C57, locale en-GB)
    • Flutter version 1.14.6 at /Users/mac/flutter
    • Framework revision fabeb2a16f (5 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B44
    • CocoaPods version 1.9.0.beta.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

**Comment by stonega** [comment]
I have the same problem with sqflite

**Comment by petermnt** [comment]
The example shows interaction with another Plugin, so it should be supported.
Please provide a simple example of this issue if you can't get it to work.

**Comment by goranristic123** [comment]
This is top level global function

```
void updateDeviceLocationIsolate() {
  Workmanager.executeTask((backgroundTask, data) async {
    try {
        // The problem is here but
        SharedPreferences prefs = await SharedPreferences.getInstance();

        if (!prefs.containsKey('user')) {
            return Future.value(true);
        }

        Position location = await Geolocator()
            .getCurrentPosition(desiredAccuracy: LocationAccuracy.high);

        final speed = location.speed > 0 ? location.speed : 1;

        if (speed > 9) {
            return Future.value(true);
        }

        setupLocator();
        await setConfig();

        final user = User.fromJson(json.decode(prefs.getString('user')));

        await debugLogToServer({
            'message': 'heartbeat location started',
            'accuracy': location.accuracy.toString(),
        });

        // ....
    } catch (e) {
        await debugLogToServer({
            'error': e.toString(),
        });

        return Future.value(false);
    }

    return Future.value(true);
  });
}
```

// main.dart
Workmanager.initialize(
    updateDeviceLocationIsolate,
    isInDebugMode: true,
);

// Registering periodic task
```
await Workmanager.registerPeriodicTask(
    "$backgroundTaskId$i",
    "clientLocationTracking-0$i",
    tag: backgroundTaskTag,
    frequency: interval,
    initialDelay: Duration(minutes: delay),
    existingWorkPolicy: ExistingWorkPolicy.replace,
    backoffPolicy: BackoffPolicy.linear,
    backoffPolicyDelay: interval,
    constraints: Constraints(
        networkType: NetworkType.connected,
    ),
);
```

Also it is not only with shared preferences If I delete that than it fails with Geolocator, so doesn't matter what plugin it is.

**Comment by petermnt** [comment]
I have tested our sample app with the following callback:

```dart
      case simpleTaskKey:
        print("$simpleTaskKey was executed. inputData = $inputData");
        final prefs = await SharedPreferences.getInstance();
        prefs.setBool("test", true);
        print("Bool from prefs: ${prefs.getBool("test")}");
        break;
```

When running the task this prints
```
I/flutter ( 4086): Bool from prefs: true
```

So I think there's another issue which makes your setup different than the sample app.
I suggest to review the sample app and compare.

**Comment by goranristic123** [comment]
I implemented example app and I get the following error message:

"Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@2f96bbe) but could not find and invoke the GeneratedPluginRegistrant".

So it's definitely problem on my end. Unrelated to this case do you know what causes this? A lot of people will face the same problem. I have fresh flutter installation this is my MainActivity.kt

```
class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}
```

And AndroidManifest.xml
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.example.spotty">
    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
        android:name="io.flutter.app.FlutterApplication"
        tools:replace="android:label"
        android:label="spotty"
        android:usesCleartextTraffic="true"
        android:icon="@mipmap/launcher_icon">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
                android:name="com.google.firebase.messaging.default_notification_icon"
                android:resource="@mipmap/launcher_icon" />
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />

            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

        <!-- Facebook Login configuration -->
        <meta-data android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id"/>

        <activity android:name="com.facebook.FacebookActivity"
            android:configChanges=
                "keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="@string/app_name" 
            android:exported="true"
            />
        <activity
            android:name="com.facebook.CustomTabActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/fb_login_protocol_scheme" />
            </intent-filter>
        </activity>
    </application>
</manifest>
```

**Comment by timrijckaert** [comment]
Might be related to https://github.com/flutter/flutter/issues/44171#issuecomment-576455708

**Comment by goranristic123** [comment]
I found out that the error happens because of the flutter_facebook_login plugin

**Comment by stonega** [comment]
> I found out that the error
> 
> ```
> Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@2f96bbe) but could not find and invoke the GeneratedPluginRegistrant
> ```
> 
> happens because of the flutter_facebook_login plugin.
> 
> I solved it by manually registering it
> 
> ```
> FacebookLoginPlugin.registerWith(registry.registrarFor("com.roughike.facebooklogin.facebooklogin.FacebookLoginPlugin"))
> ```
May ask how did you find that plugin?

**Comment by goranristic123** [comment]
I cloned example project from this repo and installed my plugins. Then I was removing them and testing at the same time to pinpoint plugins that are causing problems.

In order to register plugins manually I created Application.kt file
```
class Application : FlutterApplication(), PluginRegistry.PluginRegistrantCallback {
    override fun registerWith(registry: PluginRegistry) {
FacebookLoginPlugin.registerWith(registry.registrarFor("com.roughike.facebooklogin.facebooklogin.FacebookLoginPlugin")) 
    }
}
```
make sure to add android:name=".Application" in AndroidManifest.xml under application

**Comment by KathiriyaHP** [comment]
Any one have idea about how to call http inside of workmanager like below code have a problem like http can't receive any response and I can't found debug control at this point.("//Todo") in code

void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) async {
    switch (task) {
      case fetchBackground:

        GeolocationStatus geolocationStatus = await Geolocator().checkGeolocationPermissionStatus();
        if(geolocationStatus.value!=1){
          Position position = await Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
          Future<List<Placemark>>  placemarks = Geolocator().placemarkFromPosition(position);
          var address="";
          placemarks.then((value) {
            if(value.isNotEmpty){
              Placemark placemark = value.first;
              print("placemark : ${placemark.toJson().toString()}");
              address = "BG ${placemark.subThoroughfare} ${placemark.thoroughfare} ${placemark.subLocality} ${placemark.postalCode} ${placemark.locality} ${placemark.administrativeArea} ${placemark.country}";
              print("addresss ** =-=============> ${address}");
            }
          }).catchError((error){
          }).whenComplete(() async {
               if (inputData.containsKey("employee_id") && inputData.containsKey("token") && inputData.containsKey("attendanceType")) {
                  print("Background======Fetch  loginModel ${inputData.toString()}=======>");

                  var create_vals =
                      "{'employee_id':${inputData['employee_id']},"
                      "'latitude':'${position.latitude}',"
                      "'longitude':'${position.longitude}',"
                      "'location':'${address}',"
                      "'login_action':'${inputData['attendanceType']}',"
                      "'log_time':'${DateUtil.getCurrentDateTimeUtc()}'}";

                  print("@@@@@@@@@@@ Background value create_vals :=> ${create_vals}");

                  Map<String, String> requestHeaders = {
                    'Content-type': 'application/x-www-form-urlencoded; charset=UTF-8',

                  };

                  try{
				  //TODO : problem here api not getting any Response and i can't debug where is the control out of this method
                    final response = await http.post(Urls.DOMAIN_URL+"/api/"+Urls.EmployeeGeolocation, headers: requestHeaders, body: json.encode("{token:'${inputData["token"]}',create_vals:'${create_vals}'}"));
                    print("response==========$response");
                    if (json.decode(response.body)['Status'] == 1){
                      print("@@@@@@@@@@@ Background :=> ${json.decode(response.body)} ");
                    }
                    else
                      print("@@@@@@@@@@@ Data Not Found in background ${response.toString()}");
                  }
                  catch (error) {
                    print(error);
                  }                 
          });
        }
        else
          print("@@@@@@@@@@@@@=> Location is not active ======>");

        break;
    }
    return Future.value(true);
  });
}
