### ISSUE TITLE
🐞[Is there a chance to update my UI from callbackDispatcher]

### ISSUE THREAD

**Issue by 2math** [vrtdev/flutter_workmanager#151]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |      0.2.2         |
| Xcode version        |               |
| Swift version        |               |
| iOS deployment target|               |

**Describe the error**
Is there a chance to send messages to UI thread from BackgroundTaskHandler?

Currently my app is syncing with the server, but the UI does not update with new data until the widget is restarted. The Moor DB is updated but streams are not and I assume because the DB is updated from another isolate. There is an option to share DB btw isolates, but how can I pass DB isolate to BackgroundTaskHandler :( ?

Thanks in advance!
**Output of `flutter doctor -v`**

**Comment by nioncode** [comment]
I just went through this: you have to register a port somewhere in your widget tree where you want to receive the updates with the `IsolateNameServer` and then you can listen on that port:
```dart
var port = ReceivePort();
IsolateNameServer.registerPortWithName(port.sendPort, "yourUniqueChannelName");
port.listen((dynamic data) async {
  print('got $data on UI');
});
```

In your background task, you can then post updates to the UI isolate by doing:
```dart
final sendPort = IsolateNameServer.lookupPortByName("yourUniqueChannelName");
if (sendPort != null) {
  // The port might be null if the main isolate is not running.
  sendPort.send(['any', 'data', 'you', 'want']);
}
```

**Comment by 2math** [comment]
> I just went through this: you have to register a port somewhere in your widget tree where you want to receive the updates with the `IsolateNameServer` and then you can listen on that port:
> 
> ```dart
> var port = ReceivePort();
> IsolateNameServer.registerPortWithName(port.sendPort, "yourUniqueChannelName");
> port.listen((dynamic data) async {
>   print('got $data on UI');
> });
> ```
> 
> In your background task, you can then post updates to the UI isolate by doing:
> 
> ```dart
> final sendPort = IsolateNameServer.lookupPortByName("yourUniqueChannelName");
> if (sendPort != null) {
>   // The port might be null if the main isolate is not running.
>   sendPort.send(['any', 'data', 'you', 'want']);
> }
> ```

Sounds great, thanks!
Will test it out as soon as I'm back to the project, but it looks exactly as what I want.

**Comment by kw214** [comment]
same issue
