### ISSUE TITLE
Sqflite Error

### ISSUE THREAD

**Issue by netofontess** [vrtdev/flutter_workmanager#152]
Hi!

I am getting an error when I use it with the Sqflite plugin. I simply start my database and when I make a call with reference it presents the following error:

`E/flutter (14349): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'query' was called on null.`

I init my database in 'main()' and when i try use a query inside background task, the Database object is null... 

My code (execute has the code call 'query'):
```
void startBackgroundTask() {
    print('startBackgroundTask');
    Workmanager.registerPeriodicTask(
      "integration.1",
      "task",
      frequency: Duration(minutes: 15),
      constraints: Constraints(networkType: NetworkType.unmetered),
    );
  }

  Workmanager.initialize(
    execute,
    isInDebugMode: true,
  ).then((_) {
      startBackgroundTask();
  });
```

I saw that in some cases they fixed it by registering the plugin, but I'm not sure how to do it.

**Comment by gebsl** [comment]
You have to initialize your database in your background task. `main` will not run, if a background task is executed.
