### ISSUE TITLE
🐞[MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences]

### ISSUE THREAD

**Issue by tony123S** [vrtdev/flutter_workmanager#160]
Not sure what is going wrong

```
void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) async {
    Repository _repository = Repository();

    try {
      print("call back");
      var value = await MySharedPreferences().getUser();
      var authToken = value.auth_token;

      switch (task) {
        case Consts.UPLOAD_IMAGE:
          try {

            var response = await _repository.submit(...);          
          } catch (e) {
            print("e " + e.toString());
          }
          break;
      }
    } catch (e) {
      print(e.toString());
    }
    return Future.value(true);
  });
}
```

**sharedPrefereces**

```

  Future<User> getUser() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    User user = new User();
         .....
    return user;
  }

```
**Output**

> I/flutter (18930): call back
> I/flutter (18930): MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
> Reloaded 76 of 1372 libraries in 1,648ms.

**Comment by kvernon93** [comment]
#342 I have this same issue, kindly assist!

**Comment by mohamadhadibi** [comment]
same problem.
I just init SharedPreferences in callbackDispatcher, and here is the error: 
> E/flutter (23163): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter (23163): #0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:132:86)
E/flutter (23163): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:36)
E/flutter (23163): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:340:12)
E/flutter (23163): #3      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:367:49)
E/flutter (23163): #4      MethodChannelSharedPreferencesStore.getAll (package:shared_preferences_platform_interface/method_channel_sh
ared_preferences.dart:44:25)
E/flutter (23163): #5      SharedPreferences._getSharedPreferencesMap (package:shared_preferences/shared_preferences.dart:164:57)
E/flutter (23163): #6      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:33:19)

>

**Comment by mohamadhadibi** [comment]
> $ flutter doctor -v
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1052], locale fa-IR)
    • Flutter version 2.8.1 at F:\Softwares\fluttersdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (8 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at F:\Softwares\sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = F:\Softwares\sdk
    • ANDROID_SDK_ROOT = F:\Softwares\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\Mohad\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (3 available)
    • TA 1021 (mobile) • PLEGAR17A0710884 • android-arm64  • Android 9 (API 28)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)       • edge             • web-javascript • Microsoft Edge 91.0.864.64

• No issues found!

>
