### ISSUE TITLE
Periodtask runs inconsistently 

### ISSUE THREAD

**Issue by farazahmed7** [vrtdev/flutter_workmanager#167]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |       latest        |
| Xcode version        |               |
| Swift version        |               |
| iOS deployment target|               |

**Describe the error**
Describe error
I implemented the periodic task in my app and was testing it and saw it was very inconsistent. Most of the time the task won't even run (no notification). I thought I must be implementing it wrong but so decided to use the sample app and there it's also the same. It's very inconsistent. Most of time I don't get any notification and I have to open the app. Once I open the app the task runs.
**Output of `flutter doctor -v`**

[√] Flutter (Channel beta, v1.17.0-3.2.pre, on Microsoft Windows [Version 10.0.18362.720], locale en-IN)
    • Flutter version 1.17.0-3.2.pre at C:\flutter
    • Framework revision 2a7bc389f2 (7 days ago), 2020-04-21 20:34:20 -0700
    • Engine revision 4c8c31f591
    • Dart version 2.8.0 (build 2.8.0-dev.20.10)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\faraz.ahmed\AppData\Local\Android\sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by gebsl** [comment]
I think that's just the definition of WorkManager (on Android). The OS ensures that all your tasks will be run, but in turn, there is no guarantee it will run in a periodic way. It's not comparable to linux' cronjobs, for example, where your task will always run at the same time intervals.

**Comment by Kymer** [comment]
Yep, basically what @gebsl said.

The use case for the underling API's on Android and especially iOS is to have something recurring scheduled that eventually, might get called. On Android you can provide some more constraints and hints to when and how, but ultimately the **system** decides when to schedule what background work, not you as the developer.

**Comment by josh-gree** [comment]
So is it correct to say that there is no way to run a background task on Android on a consistent schedule? It's completely impossible?

**Comment by gebsl** [comment]
@josh-gree it's in fact impossible with this library. Actually the issue is the underlying technology. Android's workmanager has just not been designed to run tasks on a tight schedule. Also the smallest possible time between two runs is 15 minutes by design.

If you need good control over the schedule implement a foreground service or try using Android's AlarmManager, depending on the needs of your project.
