### ISSUE TITLE
Workmanager Fails After Flutter 1.18 Upgrade

### ISSUE THREAD

**Issue by AndrewChoy72** [vrtdev/flutter_workmanager#168]
Launching lib\main.dart on SM N975F in debug mode...
Running Gradle task 'assembleDebug'...
Parameter format not correct -
√ Built build\app\outputs\flutter-apk\app-debug.apk.
W/FlutterEnginePluginRegistry( 9307): Attempted to register plugin (io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry$ShimRegistrarAggregate@a561975) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@7e8ad0a).
Debug service listening on ws://127.0.0.1:61508/WkjAJYAkj18=/ws
Syncing files to device SM N975F...
W/FlutterEnginePluginRegistry( 9307): Attempted to register plugin (io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry$ShimRegistrarAggregate@9443df8) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@2c022d1).
E/MethodChannel#( 9307): Parameter messenger must not be null.
E/WM-WorkerWrapper( 9307): Work [ id=72ed176d-75d5-48d7-ba2f-0e84d4a18eab, tags={ be.tramckrijte.workmanager.BackgroundWorker } ] failed because it threw an exception/error
E/WM-WorkerWrapper( 9307): java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
E/WM-WorkerWrapper( 9307): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
E/WM-WorkerWrapper( 9307): 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
E/WM-WorkerWrapper( 9307): 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:298)
E/WM-WorkerWrapper( 9307): 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
E/WM-WorkerWrapper( 9307): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/WM-WorkerWrapper( 9307): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/WM-WorkerWrapper( 9307): 	at java.lang.Thread.run(Thread.java:919)
E/WM-WorkerWrapper( 9307): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
E/WM-WorkerWrapper( 9307): 	at io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl.<init>(MethodCallHandlerImpl.java:46)
E/WM-WorkerWrapper( 9307): 	at io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin.setupChannel(SharedPreferencesPlugin.java:35)
E/WM-WorkerWrapper( 9307): 	at io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin.registerWith(SharedPreferencesPlugin.java:20)
E/WM-WorkerWrapper( 9307): 	at technology.syswell.sperms.CustomApplication.registerWith(CustomApplication.java:22)
E/WM-WorkerWrapper( 9307): 	at be.tramckrijte.workmanager.BackgroundWorker.startWork(BackgroundWorker.kt:80)
E/WM-WorkerWrapper( 9307): 	at androidx.work.impl.WorkerWrapper$1.run(WorkerWrapper.java:281)
E/WM-WorkerWrapper( 9307): 	at android.os.Handler.handleCallback(Handler.java:883)
E/WM-WorkerWrapper( 9307): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/WM-WorkerWrapper( 9307): 	at android.os.Looper.loop(Looper.java:237)
E/WM-WorkerWrapper( 9307): 	at android.app.ActivityThread.main(ActivityThread.java:8016)
E/WM-WorkerWrapper( 9307): 	at java.lang.reflect.Method.invoke(Native Method)
E/WM-WorkerWrapper( 9307): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/WM-WorkerWrapper( 9307): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
I/WM-WorkerWrapper( 9307): Worker result FAILURE for Work [ id=72ed176d-75d5-48d7-ba2f-0e84d4a18eab, tags={ be.tramckrijte.workmanager.BackgroundWorker } ]

**Comment by Kymer** [comment]
Do you still have this issue?
