### ISSUE TITLE
⬆️ Use BGAppRefreshTask in favour of performFetch

### ISSUE THREAD

**Issue by biklas7** [vrtdev/flutter_workmanager#17]
For apps supporting iOS 13 and higher use [BGAppRefreshTask](https://developer.apple.com/documentation/backgroundtasks/bgapprefreshtask).

Check [apple documentation](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623125-application).

**Comment by timrijckaert** [comment]
@Kymer @jeremie-movify ?
Are we aware of this?

**Comment by timrijckaert** [comment]
The iOS developers are aware of this deprecation.  
Do note that this will still work on iOS 13 and will probably only be removed in later version of iOS.  

In an upcoming release we will also implement support for `BGAppRefreshTask`, I'll keep this issue open as a reminder.

**Comment by Kymer** [comment]
@biklas7 we are indeed aware of the new API and as Tim said we do plan to support in an upcoming release 👍 We wanted to focus on the old `performFetch` API first because the new tasks API is only available on iOS 13 and up.

**Comment by biklas7** [comment]
Glad to hear that, since we are planning to use this package in one of our projects. Thanks for the awesome work :rocket:

**Comment by Kymer** [comment]
We are starting to work on this. We created a new issue for tracking purposes: #109. Closing this one
