### ISSUE TITLE
Http Network call is not working  (Flutter Android)

### ISSUE THREAD

**Issue by VarmaTech** [vrtdev/flutter_workmanager#171]
Hi ,

I am using workmanager for syncing data from server using http plugin in flutter android . but nothing is happening when http is called . below i am attaching my sample for code for reference 

Sample Code : 
````
import 'dart:io';

import 'package:workmanager/workmanager.dart';
import 'package:http/http.dart' as http;

const httpSync = "httpSync";
demoBackgroundSync() {
  Workmanager.initialize(startJobs, isInDebugMode: false);
  Workmanager.registerOneOffTask("3", httpSync,
      initialDelay: Duration(seconds: 5),
      constraints: Constraints(
          networkType: NetworkType.connected,
          requiresBatteryNotLow: true,
          // requiresCharging: true,
          // requiresDeviceIdle: true,
          requiresStorageNotLow: true));
}

startJobs() {
  Workmanager.executeTask((task, inputData) {
    switch (task) {
      case httpSync:
        httpSyncApis();
        break;
    }
    print(
        "Native called background task: $task"); //simpleTask will be emitted here.
    return Future.value(true);
  });
}
Map<String, String> requestHeaders = {
        HttpHeaders.contentTypeHeader: 'application/json',
        HttpHeaders.acceptHeader: 'application/json',
        // "Access-Control-Allow-Origin": "*",
        // "Access-Control-Allow-Methods": "POST,GET,DELETE,PUT,OPTIONS"
        //  'Authorization': '<Your token>'
      };
void httpSyncApis() async{

    print('Api Request  : Started');
// till here code works but after this step nothing happening 
  var response = await http
          .get(
            'http://dummy.restapiexample.com/api/v1/employees',
            headers: requestHeaders,
          )
          .timeout(const Duration(seconds: 300));
    
    print('Response Code : ${response.statusCode}');
    print('Response Body : ${response.body}');
}

````

console logs : 
 ```
D/HostConnection(24188): HostConnection::get() New Host Connection established 0xbaf2a4a0, tid 24365
 D/HostConnection(24188): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0
 D/EGL_emulation(24188): eglMakeCurrent: 0xd5e1b4a0: ver 3 0 (tinfo 0xe9589cf0)
 I/flutter (24188): Api Request  : Started
 I/flutter (24188): Native called background task: httpSync
 I/WM-WorkerWrapper(24188): Worker result SUCCESS for Work [ id=740eaba7-dc42-4a24-b6a4-906c1218d13c, tags={ be.tramckrijte.workmanager.BackgroundWorker } ]
```

**Comment by abuzar-rasool** [comment]
I am having the same issue.

**Comment by Lukitaduarte** [comment]
Me too, any ideia?

**Comment by gebsl** [comment]
Can you try changing function `startJobs` to this:

```dart
startJobs() {
  Workmanager.executeTask((task, inputData) async {
    switch (task) {
      case httpSync:
        await httpSyncApis();
        break;
    }
    print(
        "Native called background task: $task"); //simpleTask will be emitted here.
    return true;
  });
}
```
Please note the added `async` and `await` keywords, as well as the changed return value.

This way, a future (not completed) is returned which will only complete after _awaiting_ httpSyncApis to finish.

My guess why yours is not working:

You are returning an already completed future. This might tell the system your task has finished successfully, therefore not executing further code. As your http call is async, it might be dropped by the system.

**Comment by trighomautumnatg** [comment]
I am having the same issue.

**Comment by trighomautumnatg** [comment]
> Can you try changing function `startJobs` to this:
> 
> ```dart
> startJobs() {
>   Workmanager.executeTask((task, inputData) async {
>     switch (task) {
>       case httpSync:
>         await httpSyncApis();
>         break;
>     }
>     print(
>         "Native called background task: $task"); //simpleTask will be emitted here.
>     return true;
>   });
> }
> ```
> 
> Please note the added `async` and `await` keywords, as well as the changed return value.
> 
> This way, a future (not completed) is returned which will only complete after _awaiting_ httpSyncApis to finish.
> 
> My guess why yours is not working:
> 
> You are returning an already completed future. This might tell the system your task has finished successfully, therefore not executing further code. As your http call is async, it might be dropped by the system.

it don't work

**Comment by gebsl** [comment]
Can you post parts of your code? Without it's difficult to tell what's wrong.

**Comment by yekkaplan** [comment]
this solution is not worked

> Can you try changing function `startJobs` to this:
> 
> ```dart
> startJobs() {
>   Workmanager.executeTask((task, inputData) async {
>     switch (task) {
>       case httpSync:
>         await httpSyncApis();
>         break;
>     }
>     print(
>         "Native called background task: $task"); //simpleTask will be emitted here.
>     return true;
>   });
> }
> ```
> 
> Please note the added `async` and `await` keywords, as well as the changed return value.
> 
> This way, a future (not completed) is returned which will only complete after _awaiting_ httpSyncApis to finish.
> 
> My guess why yours is not working:
> 
> You are returning an already completed future. This might tell the system your task has finished successfully, therefore not executing further code. As your http call is async, it might be dropped by the system.

**Comment by gebsl** [comment]
@yekkaplan: Same here, can you post your code?

**Comment by yekkaplan** [comment]
`void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) async {
    switch (task) {
      case fetchBackground:
        await currentLocationPost();
        break;
    }
    return true;
  });
}`

**Comment by yekkaplan** [comment]
```
void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) async {
    switch (task) {
      case fetchBackground:
        await currentLocationPost();
        break;
    }
    return true;
  });
}
```

**Comment by gebsl** [comment]
@mustafaynk 

First of all, please format you code. It's incredibly hard to read it like this.

Try this:

```dart
void callbackDispatcher() async {
  Workmanager.executeTask((taskName, inputData) async {
    switch (taskName) {
      case myTask:
        print('Alarm Control 1');

        await keysControls();
        print('Alarm Control 2');

        if (value) {
          print('Alarm Control 3');
          await getDataFromApi();
        }

        break;
    }
    return Future.value(true);
  });
}
```

Using `async` and `await` makes your code a lot more readable and should do what you want to achieve.

Why yours is not working? You are not awaiting the Future returned by method call `keysControls`, therefore the inner `await getDataFromApi();` won't do anything, as the task is cancelled before the the data is fetched.

Hope this helps.

**Comment by mustafaynk** [comment]
@gebsl Sorry for bad code format because,  I wrote first comment in GitHub. Actually, my problem is very obvious. My app request only one http request. I want to run http request method when app destroy. If you can help me, I will be very happy. Thanks for your reply. Have a good day.

**Comment by gebsl** [comment]
Hi @mustafaynk: You could try to combine this (https://flutter.dev/docs/get-started/flutter-for/android-devs#how-do-i-listen-to-android-activity-lifecycle-events) with flutter_workmanager.

Just run `Workmanager.executeTask` when the app is suspending and this should enable you to run your http call in the background.

**Comment by mustafaynk** [comment]
Hi again @gebsl ; I solved my problem. Thanks a lot.

**Comment by gebsl** [comment]
Hi @mustafaynk, can you state how you were able to solve the problem? Might also be interesting for other devs. Thanks!

**Comment by mustafaynk** [comment]
@gebsl Sure.
I called WorkManager initialize methods in initState(). WorkManager didn't work. After that, I called these methods in the 'main' method, work manager worked. Of course, I also used your advices.

**Comment by DeepaPradeepa** [comment]
Calldispatcher function does not called . Can you  help me out

**Comment by DeepaPradeepa** [comment]
void callbackDispatcher() async {
  Workmanager.executeTask((taskName, inputData) async {
    switch (taskName) {
      case fetchBackground:
        print("backgroundfetchcalled in Android");
         getcurrentlocation();
        break;
       case Workmanager.iOSBackgroundTask:
        print("backgroundfetchcalled in ios");
         break;
    }
    return true;
  });

**Comment by gebsl** [comment]
Sorry, more code needed. And please format your code, it's hard to read like this.

**Comment by DeepaPradeepa** [comment]
void callbackDispatcher() async {
  Workmanager.executeTask((taskName, inputData) async {
    switch (taskName) {
      case fetchBackground:
        print("backgroundfetchcalled in Android");
         getcurrentlocation();
        break;
       case Workmanager.iOSBackgroundTask:
        print("backgroundfetchcalled in ios");
         break;
    }
    return true;
  });
}
void getcurrentlocation() async {
   print("userLocationlatcalled");

   try {

     // Position userLocation =  await Geolocator().getCurrentPosition(
     //     locationPermissionLevel: GeolocationPermission.location,desiredAccuracy:LocationAccuracy.high);
      print("userLocationcalled}");
     AppPreferences _appPreference;
     _appPreference = App().getAppPreferences();
     final prefs = await _appPreference.getAuthToken();
     // String tokenVal;
     LatLng userLocation = LatLng(9.98,78.11);
     //);
     await updateCurrentLoc1(userLocation,prefs);
   } catch (e) {
     print('Location not shared');
   }
  //Position userLocation = await Geolocator().getCurrentPosition(desiredAccuracy:LocationAccuracy.high);


}
Future<String> updateCurrentLoc1(LatLng position,String token) async {
  FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
  new FlutterLocalNotificationsPlugin();
  var android = new AndroidNotificationDetails(
      '1', 'location-bg', 'fetch location in background',
      playSound: false, importance: Importance.Max, priority: Priority.High);
  var iOS = new IOSNotificationDetails();
  var platform = new NotificationDetails(android, iOS);

  await flutterLocalNotificationsPlugin.show(
      0, "locationtop", "${position.longitude}", platform);

  GraphQLClient graphQLClientWithHeader;
  HttpLink httpLink =
  HttpLink(uri:"http://134.209.47.247:4000/graphql",
    headers: <String, String>{
      'auth':token,
    },);
  graphQLClientWithHeader = GraphQLClient(
    cache: new InMemoryCache(),
    link: httpLink ,
  );
//print("authtoken: ${globals.authToken}");

  var variables = <String, dynamic>{
    "lat": position.latitude,
    "lng": position.longitude
  };


  Map<String, dynamic> _login_result = await getMutationValues(
      graphQLClientWithHeader,
      "updateDriverLocation_mutation",
      variables);

  if (_login_result["updateDriverLocation"]["status"] == 200) {
    print("location updated");

    await flutterLocalNotificationsPlugin.show(
        0, "locationbottom", "${position.latitude}", platform);
    //sendDriverLocation1();
    return "";
  } else if (_login_result["updateDriverLocation"]["status"] == 500) {
    print("location notupdated");
    await flutterLocalNotificationsPlugin.show(
        0, "locationerror", "${_login_result["updateDriverLocation"]["errorMessage"]}", platform);
   // sendDriverLocation1();
    return "timeout";
  } else {
    print("location notupdated reason ${_login_result["updateDriverLocation"]["errorMessage"]}");
    await flutterLocalNotificationsPlugin.show(
        0, "locationerror", "${_login_result["updateDriverLocation"]["errorMessage"]}", platform);
    return _login_result["updateDriverLocation"]["errorMessage"];
  }
}
             
              void initState() {
   // getcurrentlocation();

    Workmanager.initialize(
        callbackDispatcher,
        isInDebugMode:true
    );

    Workmanager.registerPeriodicTask(
      "1",
      fetchBackground,
      frequency: Duration(seconds:30),
    );
               }

**Comment by DeepaPradeepa** [comment]
@gebsl  Please let me know how to format my code like yours

**Comment by DeepaPradeepa** [comment]
> @gebsl Sure.
> I called WorkManager initialize methods in initState(). WorkManager didn't work. After that, I called these methods in the 'main' method, work manager worked. Of course, I also used your advices.

Hi @mustafaynk  . Can you share your worked code.

**Comment by gebsl** [comment]
@DeepaPradeepa please markup your code like this:

\`\`\`dart
var x = 'yourcodegoeshere'
\`\`\`

will then look like

```dart
var x = 'yourcodegoeshere'
```

**Comment by DeepaPradeepa** [comment]
```dart
void callbackDispatcher() async {
Workmanager.executeTask((taskName, inputData) async {
switch (taskName) {
case fetchBackground:
print("backgroundfetchcalled in Android");
getcurrentlocation();
break;
case Workmanager.iOSBackgroundTask:
print("backgroundfetchcalled in ios");
break;
}
return true;
});
}
void getcurrentlocation() async {
print("userLocationlatcalled");

try {

 // Position userLocation =  await Geolocator().getCurrentPosition(
 //     locationPermissionLevel: GeolocationPermission.location,desiredAccuracy:LocationAccuracy.high);
  print("userLocationcalled}");
 AppPreferences _appPreference;
 _appPreference = App().getAppPreferences();
 final prefs = await _appPreference.getAuthToken();
 // String tokenVal;
 LatLng userLocation = LatLng(9.98,78.11);
 //);
 await updateCurrentLoc1(userLocation,prefs);
} catch (e) {
print('Location not shared');
}
//Position userLocation = await Geolocator().getCurrentPosition(desiredAccuracy:LocationAccuracy.high);

}
Future updateCurrentLoc1(LatLng position,String token) async {
FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
new FlutterLocalNotificationsPlugin();
var android = new AndroidNotificationDetails(
'1', 'location-bg', 'fetch location in background',
playSound: false, importance: Importance.Max, priority: Priority.High);
var iOS = new IOSNotificationDetails();
var platform = new NotificationDetails(android, iOS);

await flutterLocalNotificationsPlugin.show(
0, "locationtop", "${position.longitude}", platform);

GraphQLClient graphQLClientWithHeader;
HttpLink httpLink =
HttpLink(uri:"GraphQLEndPoint",
headers: <String, String>{
'auth':token,
},);
graphQLClientWithHeader = GraphQLClient(
cache: new InMemoryCache(),
link: httpLink ,
);
//print("authtoken: ${globals.authToken}");

var variables = <String, dynamic>{
"lat": position.latitude,
"lng": position.longitude
};

Map<String, dynamic> _login_result = await getMutationValues(
graphQLClientWithHeader,
"updateDriverLocation_mutation",
variables);

if (_login_result["updateDriverLocation"]["status"] == 200) {
print("location updated");

await flutterLocalNotificationsPlugin.show(
    0, "locationbottom", "${position.latitude}", platform);
//sendDriverLocation1();
return "";
} else if (_login_result["updateDriverLocation"]["status"] == 500) {
print("location notupdated");
await flutterLocalNotificationsPlugin.show(
0, "locationerror", "${_login_result["updateDriverLocation"]["errorMessage"]}", platform);
// sendDriverLocation1();
return "timeout";
} else {
print("location notupdated reason ${_login_result["updateDriverLocation"]["errorMessage"]}");
await flutterLocalNotificationsPlugin.show(
0, "locationerror", "${_login_result["updateDriverLocation"]["errorMessage"]}", platform);
return _login_result["updateDriverLocation"]["errorMessage"];
}
}

          void initState() {
// getcurrentlocation();

Workmanager.initialize(
    callbackDispatcher,
    isInDebugMode:true
);

Workmanager.registerPeriodicTask(
  "1",
  fetchBackground,
  frequency: Duration(seconds:30),
);
           }
```

**Comment by DeepaPradeepa** [comment]
Thanks @gebsl

**Comment by gebsl** [comment]
First of all, a frequency of 30 seconds is not supported. The minimum time between two background calls is always 15 minutes (on Android). On iOS, you can not control the frequency at all (due to platform restrictions).

Secondly, put an `await` before your function call to `getcurrentlocation`, as otherwise `callbackDispatcher` will exit before running the asynchronous call.

**Comment by DeepaPradeepa** [comment]
@gebsl  Yes I know that time interval which is defaultly taken as 15 mins. I tried with await callbackDispatcher as well. But I am getting failure status background fetch Pushnotification

**Comment by gebsl** [comment]
@DeepaPradeepa, have you already tried the example project to verify whether this one works or not?

**Comment by DeepaPradeepa** [comment]
@gebsl  Yes. I tried with local push notification which is worked fine. But Now API Call  functionality does not work

**Comment by gebsl** [comment]
I just realize we are probably not talking about the same thing. 

> @gebsl Yes I know that time interval which is defaultly taken as 15 mins. I tried with await callbackDispatcher as well. But I am getting failure status background fetch Pushnotification

I proposed awaiting `getcurrentlocation`, but you wrote you awaited `callbackDispatcher`. That could be the problem.

**Comment by DeepaPradeepa** [comment]
> I just realize we are probably not talking about the same thing.
> 
> > @gebsl Yes I know that time interval which is defaultly taken as 15 mins. I tried with await callbackDispatcher as well. But I am getting failure status background fetch Pushnotification
> 
> I proposed awaiting `getcurrentlocation`, but you wrote you awaited `callbackDispatcher`. That could be the problem.

Sorry @gebsl  I wrongly told  ```dart await  callbackDispatcher ```. I have tried with ```dart await getcurrentlocation() ```. Same thing happened. Now I tried with native iOS Callback with Flutter. Thank you very much for helping.

**Comment by gebsl** [comment]
Oh, your issue is on iOS? I didn't know this. This whole thread is about workmanager on Android.

**Comment by Gerhardt0011** [comment]
Had the same issue, managed to resolved the issue with the following code. 

In main()
` Workmanager().registerPeriodicTask(
      "update_location_worker", "update_location_worker",
      frequency: Duration(minutes: 15),
      inputData: {
        "lat": UserSharedPrefs.getLat(),
        "long": UserSharedPrefs.getLong()
      },
      initialDelay: Duration(minutes: 1),
      constraints: Constraints(
        networkType: NetworkType.connected,
      ));`

Before the main() method i have this function 

`void callbackDispatcher() {
  Workmanager().executeTask((taskName, inputData) async {
    await UserSharedPrefs.init();
    Position position = await Geolocator.getCurrentPosition();
    UserSharedPrefs.setLat(position.latitude);
    UserSharedPrefs.setLong(position.longitude);

    final String url = 'https://72b7-154-70-228-141.ngrok.io';
    final String path = 'api/lat_long_store';

    var bearerToken = UserSharedPrefs.getBearerToken();

    var headers = {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
      'Authorization': 'Bearer $bearerToken'
    };

    final body = {'lat': position.latitude, 'long': position.longitude};

    await http.post(
      Uri.parse(url + '/' + path),
      headers: headers,
      body: jsonEncode(body),
    );

    LocalNotification.Initializer();
    LocalNotification.ShowOneTimeNotification(DateTime.now());
    return Future.value(true);
  });
}`

see screenshot attached, this is making a http post request :) 
![image](https://user-images.githubusercontent.com/17843787/152631013-161f9785-470e-4b80-9684-7a617cbdb9c2.png)
