### ISSUE TITLE
is this suitable?

### ISSUE THREAD

**Issue by aldwnesx** [vrtdev/flutter_workmanager#173]
My app has a timer running. However when user locks the phone or the app goes tobackgroudn the timer stops. It continues when I open the app again.

I was thinking of using this package as a substitute.

Every 15 mins it get called, and I wil do some calculation e.g if user sets 30 mins timer, then this background fetch runs about every 15 mins so I just have a variable to keep track how many times it has run.... does this solve my requirement?

I only need the timer to work when the app is in background and/or the phone is locked.

IF the app is terminated it shouldn't do anything.

**Comment by Kymer** [comment]
No that requires too much 'precision'. The use case for the underling API's on Android and especially iOS is to have something recurring scheduled that eventually, might get called. On Android you can provide some more constraints and hints to when and how, but ultimately the system decides when to schedule what background work.
