### ISSUE TITLE
Other plugins failing when called in background IOS

### ISSUE THREAD

**Issue by edsonboldrini** [vrtdev/flutter_workmanager#174]
In Android everything works fine, but in iOS this error happens every time the callback dispatcher is called:
```
Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
```
Other plugins show the same error message, only iOS.

**Comment by gebsl** [comment]
Please have a look at the example provided by vrtdev 
https://github.com/vrtdev/flutter_workmanager/blob/master/example/ios/Runner/AppDelegate.swift

You need to include these lines for other plugins to work in your background task:

```swift
WorkmanagerPlugin.setPluginRegistrantCallback { registry in
  // registry in this case is the FlutterEngine that is created in Workmanager's performFetchWithCompletionHandler
  // This will make other plugins available during a background fetch
  GeneratedPluginRegistrant.register(with: registry)
}
```

Unfortunately this is not mentioned in the iOS setup guide.

**Comment by Kymer** [comment]
> Unfortunately this is not mentioned in the iOS setup guide.

It is though: https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md#registered-plugins

**Comment by gebsl** [comment]
> It is though: https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md#registered-plugins

Oops, sorry, completely missed this one.
