### ISSUE TITLE
not working on iOS

### ISSUE THREAD

**Issue by cahyofendhi** [vrtdev/flutter_workmanager#175]
the plugin work for android but i try to iOS have error and not working, i read again on documentation but android only, are there function for iOS ? or the plugin just for android

**Comment by gebsl** [comment]
Here you go:

https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md

**Comment by Kymer** [comment]
> but not work

Okay.

Please file a new ticket with the bug report template and provide more details.
