### ISSUE TITLE
Debug Failure Result

### ISSUE THREAD

**Issue by adolfdsilva** [vrtdev/flutter_workmanager#176]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology                   | Version       |
| -------------------      | ------------- |
| Workmanager version  |       0.2.0        |
| Android version            |       9.0           |
| Android Model              |       Xiaomi Redmi Note 5 Pro |

**Describe the error**
Is there a way to debug failure result.
I'm using `SharedPreference` Plugin  in the callback.
![Screenshot_2020-05-29-11-48-02-687_jpg](https://user-images.githubusercontent.com/6647993/83222925-c67c5680-a1a3-11ea-8b2c-5cc932465324.jpg)

**Output of `flutter doctor -v`**
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-KH)
    • Flutter version 1.17.1 at /Users/adolfdsilva/Documents/Workspace/Flutter/sdk
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/adolfdsilva/Library/Android/sdk/
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/adolfdsilva/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[!] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (2 available)
    • Redmi Note 5 Pro          • 543ddcc8      • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 10 (API 29) (emulator)

**Comment by gebsl** [comment]
I can only advice using dart's function `print` to log messages.

Example: 
```dart
print('Debug message');
```
At least this is the way how i debug WorkManager on Android. You can see the output in your debug console or alternatively using Android's LogCat.

**Comment by rmahmadkhan** [comment]
Hey @adolfdsilva 
I'm also facing this issue now while accessing Prefs. How did you get it right?

**Comment by adolfdsilva** [comment]
@rmahmadkhan ah I ended up removing this lib as it was no longer necessary for our business requirement.

**Comment by rmahmadkhan** [comment]
@Kymer Looking for a workaround here. Any tips?

**Comment by gebsl** [comment]
@rmahmadkhan without providing at least some logs or debug output nobody will be able to help you I guess...

**Comment by rmahmadkhan** [comment]
> @rmahmadkhan without providing at least some logs or debug output nobody will be able to help you I guess...

I'm having the exact issue which Adolf had.

This is what I'm getting in debug console

`Worker result FAILURE for Work [ id=6ba168ca-036d-4f20-9f69-5d50fcfbdf45, tags={ be.tramckrijte.workmanager.BackgroundWorker } ]`

**Comment by gebsl** [comment]
@rmahmadkhan did you spedify any custom debug logs with `print('log')`?
Apart from that, have you already tried running the example application provided in this repo?
