### ISSUE TITLE
🐞 iOS: Fix memory leak in performFetchWithCompletionHandler

### ISSUE THREAD

**Issue by Kymer** [vrtdev/flutter_workmanager#19]
In the `performFetchWithCompletionHandler` a `FlutterMethodChannel` is created and strongly captured inside the `setMethodCallHandler` block, causing it to never be released. See memory usage here:
<img width="1164" alt="Screenshot 2019-08-08 at 16 18 07" src="https://user-images.githubusercontent.com/9093854/62710751-25e05e80-b9f8-11e9-9c01-6a2163c66f25.png">

**Comment by petermnt** [comment]
I verified on Android and there the cleanup happens correctly because the only reference is inside the Worker, which will get properly cleaned up after GC.
