### ISSUE TITLE
Why does not it appear when I set up Flutter notifications with workmanager

### ISSUE THREAD

**Issue by StatTark** [vrtdev/flutter_workmanager#190]
I want to pull a data from the database and show it in notifications. I use the workmanager package to get the notification when I close the application. Code snippets continue to run in the background. But even if I enter the duration as 5 seconds, what might be the reason why the notification comes after a long time.

```
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:takvim_app/databasehelper/DataBaseHelper.dart';
import 'screens/mainmenu.dart';
import 'package:workmanager/workmanager.dart';

const simplePeriodicTask = "simplePeriodicTask";

void showNotification( v, flp) async {
  var android = AndroidNotificationDetails(
      'channel id', 'channel NAME', 'CHANNEL DESCRIPTION',
      priority: Priority.High, importance: Importance.Max);
  var iOS = IOSNotificationDetails();
  var platform = NotificationDetails(android, iOS);
  await flp.show(0, 'Virtual intelligent solution', '$v', platform,
      payload: 'VIS \n $v');
}

void callbackDispatcher() {
  var db = DbHelper();
  Workmanager.executeTask((task, inputData) async {

    FlutterLocalNotificationsPlugin flp = FlutterLocalNotificationsPlugin();
    var android = AndroidInitializationSettings("app_icon");
    var iOS = IOSInitializationSettings();
    var initSetttings = InitializationSettings(android, iOS);
    flp.initialize(initSetttings);
    var events = await db.getEventList();
    var event = events[0];
    var datetime = DateTime.now().toString();
    showNotification(datetime, flp);
    return Future.value(true);
  });
}

Future<void> main() async{
  WidgetsFlutterBinding.ensureInitialized();
  await Workmanager.initialize(callbackDispatcher, isInDebugMode: false); //to true if still in testing lev turn it to false whenever you are launching the app
  await Workmanager.registerPeriodicTask("5", simplePeriodicTask,
    existingWorkPolicy: ExistingWorkPolicy.replace,
      frequency: Duration(seconds: 2),//when should it check the link
      initialDelay: Duration(seconds: 5),//duration before showing the notification
      constraints: Constraints(
        networkType: NetworkType.connected,
      )
  );
  runApp(MaterialApp(
      debugShowCheckedModeBanner: false, title: "Takvim", home: MainMenu()));
}
```

**Comment by yakupbaser** [comment]
because the android devices do not allow more than 15 minutes in background services. Btw i use Workmanager with periodic task and my dispatch method works in smilator but doesnt work on device. (Device options are done)

**Comment by StatTark** [comment]
@yakupbaser My main goal was to show a countdown in notifications.  I guess I can't do this directly with flutter.  That's why I'm trying to write as native.  Is it possible to show a countdown in notifications?  if possible can you give me an idea  Can the countdown be shown as a progress bar?  The most important thing is that the countdown still appears when the app is closed.

**Comment by gebsl** [comment]
Have a look at this article: https://dev.to/protium/flutter-background-services-19a4

I think this could be exactly what you are looking for. The use of Android's services is more appropriate, if you want to design a countdown that can also run in background. Android's WorkManager is not designed to do tasks like yours.
