### ISSUE TITLE
Update iOS install instructions

### ISSUE THREAD

**Issue by cormalenv** [vrtdev/flutter_workmanager#191]
Is it worth adding in an example instruction for AppDelegate.m as well as swift? For newby's like me took a couple of hours to work out. Sorry I am not up on PRs yet.

`- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
   ....
    [[UIApplication sharedApplication] setMinimumBackgroundFetchInterval:60*15];
   ...
}`

**Comment by Kymer** [comment]
As newbie you should generate your project using Swift. If you have a good reason to use Objective C over Swift, you generally know how to write Objective C.

**Comment by cormalenv** [comment]
OK. Some plugins include both but I appreciate it is up to you. Its documented here then at least for those that need it.
