### ISSUE TITLE
🐞[AppDelegate.swift:3:8: error: no such module 'workmanager']

### ISSUE THREAD

**Issue by VadPinchuk** [vrtdev/flutter_workmanager#192]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)

**0.2.3**

**No success in pod install**
I have tried to do all steps from iOS installation, but still cant run application on iOS simulator.
Workmanager module not found.
What can be an issue?

**Doctor**
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-UA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
[✓] Connected device (1 available)

**Comment by congfandi** [comment]
hi guys ? i got this error.. any suggestion for me ?

**Comment by Rnekkanti-syncro** [comment]
I am facing this error after migrating the iOS Podfile. Any suggestion @VadPinchuk

**Comment by emouawad** [comment]
Any solution for this? noticed the issue is closed? getting the same.

**Comment by armanhadifatah** [comment]
I have same problem
