### ISSUE TITLE
🐞[iOS background work]

### ISSUE THREAD

**Issue by VadPinchuk** [vrtdev/flutter_workmanager#193]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Way to work with background on iOS**
For now there is only one task name, which might be triggered by iOS on its own. Is there a way to queue specific background task on iOS, like in Android (runOneOffTask) ?

**Comment by Kymer** [comment]
Not currently (see #109)
