### ISSUE TITLE
"variable declaration in when subject" only supported since 1.3

### ISSUE THREAD

**Issue by vanlooverenkoen** [vrtdev/flutter_workmanager#25]
Failed to compile version 0.0.12

```
android/src/main/kotlin/be/tramckrijte/workmanager/WorkmanagerCallHandler.kt: (22, 19): The feature "variable declaration in when subject" is only available since language version 1.3
```

If you are having this issue. Upgrade your Kotlin version of 1.3 or above.

**Comment by timrijckaert** [comment]
You would only need to do this if you want to build the code yourself.

**Comment by vanlooverenkoen** [comment]
I have a project that still used 1.2.71 and it gave me the error. So I upgraded my project to kotlin 1.3.41 and it was fixed.

**Comment by monajafi** [comment]
where should we upgrade kotlin version in flutter project I have installed the latest version of kotlin on my mac

**Comment by vanlooverenkoen** [comment]
Your kotlin version in your android project inside your flutter project should be at least at 1.3.0

**Comment by monajafi** [comment]
should I change the   implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
in app level build.gradle file?

**Comment by vanlooverenkoen** [comment]
You could change all `$kotlin_version` to the latest version. or you could just change the variable in yout build.gradle in the android root project. Not in your app module.

**Comment by monajafi** [comment]
thanks it fixed the kotlin version error now I have to fix the gradle version too
