### ISSUE TITLE
📝 Interval duration lesser than minimum allowed value; Changed to 900000

### ISSUE THREAD

**Issue by vanlooverenkoen** [vrtdev/flutter_workmanager#26]
Android Jetpack automatically changes your interval to 15min or `900000` 

This should be documented here as well. People who are using this plugin will not necessarily know that this is the case. Although Jetpack prints out:

`W/WM-WorkSpec(13916): Interval duration lesser than minimum allowed value; Changed to 900000`

I think it should be documented somewhere as well.

**Comment by timrijckaert** [comment]
We actually [document](https://pub.dev/documentation/workmanager/latest/workmanager/Workmanager/registerPeriodicTask.html)ed this behaviour already on the `registerPeriodicTask` method.  
It could however be improved and might also be repeated on the `README`

Feel free to update and send us a PR.

**Comment by jepperaskdk** [comment]
Is there no way to run this at a lower frequency, e.g. for development?
