### ISSUE TITLE
Can't get the iOS version to work. Help needed

### ISSUE THREAD

**Issue by matejthetree** [vrtdev/flutter_workmanager#45]
Hey guys,

I tried to run the example as well as my own version. Android works fine but I can't get the simulator to run notifications never. Is there some trick with simulator or do I have to use real device?

Also, the option to dispatch fetch in xcode is greyed out for me, so I couldn't try that one from the docs.

**Comment by Kymer** [comment]
>  Is there some trick with simulator or do I have to use real device?

Notifications are only visible on real devices, yes. That's because of a limitation of the iOS simulator, not a decision by us 🙂 But we should definitely add that to our documentation and improve logging when we detect the app is running on a simulator. I'll open a separate issue for that.

> Also, the option to dispatch fetch in xcode is greyed out for me

Which Xcode version are you using? @jeremie-movify told me he had the same issue with some version of Xcode. But for me on **Xcode 10.3** (latest stable version of Xcode) the option is working fine (I even assigned it to <KBD>CTRL</KBD> + <KBD>F</KBD> for easier access) 👇

<img width="331" alt="Screenshot of Xcode's Debug menu" src="https://user-images.githubusercontent.com/9093854/63294346-5bbff580-c2ca-11e9-859f-3c07b5a89b7b.png">

**Comment by matejthetree** [comment]
Ok. I connected with debugger by attaching to runner process. And I also tried with running the project from x-code. I still get no notifications on the example app. 

X-code 10.3.
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G84, locale en-HR)
version: 0.0.14 of library

**Comment by Kymer** [comment]
Ok so, attaching the debugger enabled the _Simulate Background Fetch_ for you in the Debug menu? Glad to hear that worked 👍

As for the notifications not being visible: I think I know what is going on. If the example app is running in the **foreground** while you simulate a background fetch in Xcode, the notification banner isn't shown. That is default behaviour on iOS. Try the following steps:

1. Run the example app from Xcode (or make sure the debugger is attached)
2. In Simulator go _Home_ while the app is actively running
   - Via Home button click / Home indicator swipe, or menu `Hardware → Home` or keyboard shortcut <kbd>⌘ command</kbd> + <kbd>⇧ shift</kbd> + <kbd>H</kbd>
3. Do the _Simualte Background Fetch_ in Xcode; you should now see the notification banners appear like so👇

<img width="387" alt="Screenshot of iOS Simulator showing notification banner on Home screen" src="https://user-images.githubusercontent.com/9093854/63389895-833bbe80-c3ad-11e9-8aea-df5be9ec4132.png">

Triggering _Simulate Background Fetch_ when running on a real device will put the app in the background automatically for you. This doesn't happen in the simulator for some reason 🤷‍♂️ 

Alternatively, if you *do* want the banners to appear while your app is in the foreground you can implement `userNotificationCenter(_:willPresent:withCompletionHandler:)` of `UNUserNotificationCenterDelegate`.

From the [Apple docs](https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649518-usernotificationcenter):

> If your **app is in the foreground** when a notification arrives, the shared user **notification center calls this method to deliver the notification directly to your app**. If you implement this method, you can take whatever actions are necessary to process the notification and update your app. When you finish, **call the completionHandler block and specify how you want the system to alert the user**, if at all.

An easy way to get it working is by implementing it your `AppDelegate` like so:
```
extension AppDelegate: UNUserNotificationCenterDelegate {
    
    func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
        completionHandler(.alert)
    }
}
```

And assigning yourself as the delegate. Preferably as early as possible, in `application:didFinishLaunchingWithOptions:`

```
UNUserNotificationCenter.current().delegate = self
```

Now the banners **are** shown when your app is running in the foreground 👇
<img width="387" alt="Screenshot of iOS Simulator showing notification banner on top of running example app" src="https://user-images.githubusercontent.com/9093854/63390813-a7e56580-c3b0-11e9-8199-0fb9d959adfe.png">

It's definitely something we should mention in our documentation. The example app should implement this delegate call as well.

Anyway, I hope this helps, and thank you for bringing this to our attention 👍 Unless you have any more problems I will close this issue.
