### ISSUE TITLE
Can I use phone_state_i package to check on call state when app is not running?

### ISSUE THREAD

**Issue by john-ravi** [vrtdev/flutter_workmanager#49]
[I want to detect phone state in android using ](https://pub.dev/packages/phone_state_i) while running in background. 
I could make periodic task execute every 15 min. But I would like to listen to phone state as and when it changes and then call dart code. Below is screenshot of code running at 15 min interval.
![periodic 15](https://user-images.githubusercontent.com/44191207/63419664-d3a13380-c422-11e9-83a3-4b58eb91b18d.jpg)

**Comment by timrijckaert** [comment]
This is not the intended use case for this package.  
You could schedule a job that will run every 15 minutes like you said, but this is not ideal:
- You lose the reactive nature of the plugin which will notify you as soon as a new state is received
- You are not guaranteed that your task will run every 15 minutes by neither Android nor iOS.

If you want such a feature it is better to develop this using other native constructs like BroadCast Receivers on Android.
