### ISSUE TITLE
Is it possible to use the plugin for data sync in background like the way firebase does

### ISSUE THREAD

**Issue by monajafi** [vrtdev/flutter_workmanager#51]
I wonder how is possible to sync offline data with server like  firebase does in background especially in iOS . with OneOffTask by network connected constraint we can do it easily in android but in iOS we have just fetch in background can we use that for this purpose? If not and If the iOS has restricted this, how the firebase does syncing in iOS

**Comment by Kymer** [comment]
Yes sure, on iOS you can do some syncing work within background fetch's time window of 30 seconds, but it is never _guaranteed_ to run (neither by Android for that matter):

From [Apple's `performFetchWithCompletionHandler` docs](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623125-application) (_emphasis mine_):
> When this method is called, **your app has up to 30 seconds of wall-clock time to perform the download operation** and call the specified completion handler block. In practice, your app should **call the completion handler block as soon as possible** after downloading the needed data. If you do not call the completion handler in time, your app is terminated. More importantly, the system uses the elapsed time to calculate power usage and data costs for your app’s background downloads. **If your app takes a long time to call the completion handler, it may be given fewer future opportunities to fetch data in the future**.

As mentioned in our [iOS readme](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md#testing-background-fetch); you as a developer have no control over _when_ and _how often_ iOS will allow your app to fetch/sync data in the background. So don't **rely** on it happening.

Make sure your app is built robustly enough to account for this and has alternative approaches set-up (combining background fetch with [silent push notifications](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app) for example).

I hope this helps 👍 Unless you have any more questions, I will close this issue.
