### ISSUE TITLE
App crashes during initialisation of task

### ISSUE THREAD

**Issue by KeaSoft** [vrtdev/flutter_workmanager#53]
I tried to integrate the dummy code example in my App: 

``` 
void callbackDispatcher() {
  Workmanager.executeTask((backgroundTask) {
    print("Native called background task: $backgroundTask"); //simpleTask will be emitted here.
    return Future.value(true);
  });
}

void main() {
  Workmanager.initialize(
    callbackDispatcher, // The top level function, aka callbackDispatcher
    isInDebugMode: true // If enabled it will post a notification whenever the task is running. Handy for debugging tasks
  );
  Workmanager.registerOneOffTask("1", "simpleTask");
  runApp(MyApp());
}
```
But I got the following error while starting: 

```
E/AndroidRuntime(27923): kotlin.UninitializedPropertyAccessException: lateinit property pluginRegistryCallback has not been initialized
E/AndroidRuntime(27923): 	at be.tramckrijte.workmanager.WorkmanagerPlugin$Companion.getPluginRegistryCallback(WorkmanagerPlugin.kt:13)
E/AndroidRuntime(27923): 	at be.tramckrijte.workmanager.BackgroundWorker$doWork$1.run(BackgroundWorker.kt:71)
E/AndroidRuntime(27923): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime(27923): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(27923): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(27923): 	at android.app.ActivityThread.main(ActivityThread.java:6682)
E/AndroidRuntime(27923): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27923): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
E/AndroidRuntime(27923): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by timrijckaert** [comment]
It seems like you did not read the README.
You'll need to follow the directions under the `Platform Setup`

**Comment by SherwinJames** [comment]
Does the same Android Setup apply with Flutter Android Embedding V2 (Flutter version >= 1.12)?  Can't seem to get that Android SETUP code to compile.

[√] Flutter (Channel beta, v1.12.13+hotfix.6, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.41.1)
[√] Connected device (1 available)

**Comment by d9media** [comment]
flutterEmbedding in AndroidManifest.xml is present but my app still keeps crashing. Were you able to solve it, KeaSoft?

**Comment by emouawad** [comment]
@d9media same issue and i have flutterembedding in AndroidManifest.xml

**Comment by paraslamsong** [comment]
Have anyone solved this? 
I am getting same after running workmanager, it gives notification of success but app crashes.

Android and iOS setup is done as per in Readme file

**Comment by casualcoder404** [comment]
Please reopen this issue as many of us are still facing this issue even after having :

kotlin version '1.4.+'
and
<meta-data
    android:name="flutterEmbedding"
    android:value="2" />

**Comment by ZhangXingXingo** [comment]
Im sure that my kotlin version is 1.6.10 but still have this question
