### ISSUE TITLE
IOS pod install error

### ISSUE THREAD

**Issue by erolasan** [vrtdev/flutter_workmanager#57]
Hi,
I am getting this error when trying to run the app on IOS.

```
Unable to determine Swift version for the following pods:
    - `workmanager` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set.
Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

**Comment by Kymer** [comment]
Interesting. Are you integrating this in a project that doesn’t use Swift?

**Comment by hksunnylaw** [comment]
Hi erolan

Please try the below method:
Try to open the iOS project in the folder ios/Runner/Runner.xcworkspace with XCode and then just add a new swift file anywhere (choose File -> New -> File -> Swift File), XCode will ask you if you wish to create Bridging Header, click yes.

**Comment by erolasan** [comment]
Thanks, this worked.
Also, in the example it says that periodic tasks are Android only. Does that mean that you cannot schedule periodic tasks on IOS?

**Comment by timrijckaert** [comment]
iOS' performfetch already scheduled a periodic task for you, but you don't control the frequency. In typical Apple fashion, they decide when it will run. 

However you can optionally decide the frequency you'd like. 
See the setup for iOS in the README.

**Comment by Kymer** [comment]
Thanks @hksunnylaw for your input. That‘s a good temporary workaround 👏

But ideally the plugin should work with non-Swift projects _out of the box_. I created a new issue.

**Comment by LawreneEdung** [comment]
> Hi erolan
> 
> Please try the below method: Try to open the iOS project in the folder ios/Runner/Runner.xcworkspace with XCode and then just add a new swift file anywhere (choose File -> New -> File -> Swift File), XCode will ask you if you wish to create Bridging Header, click yes.

Amazing this worked for me. Thank you so much
