### ISSUE TITLE
⬆️ iOS: Plugin should work in ObjC-only projects

### ISSUE THREAD

**Issue by Kymer** [vrtdev/flutter_workmanager#58]
As mentioned in issue #57: the Workmanager plugin should work _out of the box_ with ObjC-only projects. Currently you get the following error when running `pod install`:

```
Unable to determine Swift version for the following pods:
    - `workmanager` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set.
Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

**Comment by otopba** [comment]
@Kymer Could you provide all source code of your sample app?
I created sample app with objc code and everything works well

**Comment by Kymer** [comment]
Hey, sorry for slow response.

I filed this issue because someone else had an issue in an Obj-C only project (#57). I haven’t had time yet to investigate deeper or try to reproduce the error. I created this issue more of a reminder for myself :)

Are you saying you are unable to reproduce the error in a project that doesn’t contain any Swift files? If so that’s the case I’ll close this issue 💁‍♂️

**Comment by otopba** [comment]
@Kymer 
Yes, everything works fine in a project without swift files. I checked

**Comment by jinfagang** [comment]
```
 `workmanager` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWI
```

Please fix this
