### ISSUE TITLE
[Question] Android custom application

### ISSUE THREAD

**Issue by hanabi1224** [vrtdev/flutter_workmanager#60]
Regarding Android setup process, is it possible to add default working custom application to plugin so that ppl only need to change application name and save the step to create an application class everytime?

**Comment by timrijckaert** [comment]
How would you see this?  
You would need to know the implementer package name in order to provide a default app.
The problem is the import. 

`package replace.me.with.your.package.name`

**Comment by hanabi1224** [comment]
@timrijckaert You can provide the full name of the custom application in the documentation of this plugin right?  It's the same way how default 'io.flutter.app.FlutterApplication' works, the flutter project template provides the name and does not require people to explicitly inherit their application from it

**Comment by timrijckaert** [comment]
So you save 1 step?
You will still need to edit the `AndroidManifest` file to point to ours.

Is it really such a burden to make a custom `Application` class?  
In the end most applications will have their custom `Application` class anyway. It would be nicer if we could somehow use composition of `Application` classes, but unfortunately that's not how Android works. 

I'll discuss this in team.

**Comment by timrijckaert** [comment]
I just discussed in team.  
We decided we think the current implementation is sufficient.
