### ISSUE TITLE
Airplane mode overnight cancels periodictask?

### ISSUE THREAD

**Issue by MiguelSOliveira** [vrtdev/flutter_workmanager#61]
I'm running a periodic task and it works perfectly. However during the night I usually turn on airplane mode and turn it off in the morning. From that point on I do not receive notifications again.

**Comment by Kymer** [comment]
Are you using an Android or iOS device?

**Comment by MiguelSOliveira** [comment]
Android

**Comment by timrijckaert** [comment]
Android guarantees the job will be called eventually.  
It can however that depending on which BackOffPolicy you used that the next retry is delayed longer in to the future.
