### ISSUE TITLE
Will the task be executed after killing the app?

### ISSUE THREAD

**Issue by edsonboldrini** [vrtdev/flutter_workmanager#68]
If I register a task with a 5-minute initial delay and killing the app before this time reaches, will the task still be executed?

**Comment by timrijckaert** [comment]
Yes

**Comment by edsonboldrini** [comment]
How can I debug the task scheduled to run when the app is already killed?

**Comment by timrijckaert** [comment]
We provide you with a notification that will show whether your Dart code ran successfully or not. 

As for the specific Dart logic that will run you can easily just test it like any other logic with unit tests.

**Comment by edsonboldrini** [comment]
Thank you! Everything seems to work fine!

**Comment by anil-sookshum** [comment]
@edsonboldrini  How did you manage to work when the app is killed/not opened. I am having the issue while the app is not opened but working fine when the app is running.
