### ISSUE TITLE
UninitializedPropertyAccessException: lateinit property pluginRegistryCallback has not been initialized E

### ISSUE THREAD

**Issue by gbmiranda** [vrtdev/flutter_workmanager#70]
E/AndroidRuntime(28568): kotlin.UninitializedPropertyAccessException: lateinit property pluginRegistryCallback has not been initialized
E/AndroidRuntime(28568):        at be.tramckrijte.workmanager.WorkmanagerPlugin$Companion.getPluginRegistryCallback(WorkmanagerPlugin.kt:13)
E/AndroidRuntime(28568):        at be.tramckrijte.workmanager.BackgroundWorker$doWork$1.run(BackgroundWorker.kt:71)
E/AndroidRuntime(28568):        at android.os.Handler.handleCallback(Handler.java:789)
E/AndroidRuntime(28568):        at android.os.Handler.dispatchMessage(Handler.java:98)
E/AndroidRuntime(28568):        at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(28568):        at android.app.ActivityThread.main(ActivityThread.java:6944)
E/AndroidRuntime(28568):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28568):        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/AndroidRuntime(28568):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by timrijckaert** [comment]
#53

**Comment by gbmiranda** [comment]
Thx
