### ISSUE TITLE
Handle notifications

### ISSUE THREAD

**Issue by MarceloRab** [vrtdev/flutter_workmanager#74]
Congratulations for the work. This is the only background solution I know.

Could you give us the freedom to configure the notification that appears after starting the service? How to choose the icon, title and be able to generate a link by clicking on it? How to generate a link to open the app.

**Comment by timrijckaert** [comment]
Sorry but this is not the main focus of this plugin.

The debug notification is there for debugging not to be styled by the implementor.

Is there anything in particular information you are missing?

**Comment by MarceloRab** [comment]
Sorry, I didn't quite understand that you could cancel the notification by removing debug mode.

I am associating your puglin with package: android_intent / android_intent.dart and package: flutter_local_notifications. This makes the connection between the service and the user.

Thank you very much for your attention.
