### ISSUE TITLE
Erro start - service

### ISSUE THREAD

**Issue by MarceloRab** [vrtdev/flutter_workmanager#77]
workmanager: ^0.1.1

E/AndroidRuntime( 6854): kotlin.UninitializedPropertyAccessException: lateinit property pluginRegistryCallback has not been initialized

[√] Flutter (Channel master, v1.10.2-pre.83, on Microsoft Windows [versÃ£o 10.0.18362.356], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.37.0)
[√] Connected device (1 available)

**Comment by timrijckaert** [comment]
#53

**Comment by MarceloRab** [comment]
But in the version workmanager: ^0.1.2 is not done this way.  

See - https://github.com/vrtdev/flutter_workmanager/blob/master/example/lib/main.dart

**Comment by MarceloRab** [comment]
I am already grateful for the attention. As I was testing the new version, I ended up having trouble testing the workmanager package version: ^ 0.1.1 trying to implement as in the workmanager version: ^ 0.1.2.

**Comment by MarceloRab** [comment]
You do a great job.
