### ISSUE TITLE
Could you upload version 0.1.2 to pub please?

### ISSUE THREAD

**Issue by otopba** [vrtdev/flutter_workmanager#78]
With this PR =)
https://github.com/vrtdev/flutter_workmanager/pull/79

**Comment by timrijckaert** [comment]
I wanna see if we can bundle some more issues first.
- Java support 
- Objective C support

**Comment by otopba** [comment]
@timrijckaert Hi!
So, I checked and we have no problems with Swift/Java. What kind of support you want of Obj-c?
