### ISSUE TITLE
App throws exception with simple task

### ISSUE THREAD

**Issue by ahmed56734** [vrtdev/flutter_workmanager#80]
I can't get to run ths library
this is how  I configured my App class "App.java"

```import be.tramckrijte.workmanager.WorkmanagerPlugin;
import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class App extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback{
    @Override()
    public void onCreate() {
        super.onCreate();
        WorkmanagerPlugin.setPluginRegistrantCallback(this);
    }

    @Override()
    public void registerWith(PluginRegistry reg) {
        GeneratedPluginRegistrant.registerWith(reg);
    }
}
```
this the code I ran just like the readme
```
    Workmanager.initialize(
        callbackDispatcher, // The top level function, aka callbackDispatcher
        isInDebugMode:
            true // If enabled it will post a notification whenever the task is running. Handy for debugging tasks
        );
    Workmanager.registerOneOffTask("1", "simpleTask");
```

and this is the error I am getting
```
E/AndroidRuntime( 8906): FATAL EXCEPTION: main
E/AndroidRuntime( 8906): Process: com.tafeel.full.masar4, PID: 8906
E/AndroidRuntime( 8906): java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Application android.app.Activity.getApplication()' on a null object reference
E/AndroidRuntime( 8906): 	at com.github.adee42.keyboardvisibility.KeyboardVisibilityPlugin.registerWith(KeyboardVisibilityPlugin.java:107)
E/AndroidRuntime( 8906): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:33)
E/AndroidRuntime( 8906): 	at com.tafeel.masar_4_flutter.App.registerWith(App.java:20)
E/AndroidRuntime( 8906): 	at be.tramckrijte.workmanager.BackgroundWorker$doWork$1.run(BackgroundWorker.kt:71)
E/AndroidRuntime( 8906): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime( 8906): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 8906): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 8906): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime( 8906): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8906): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 8906): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by ahmed56734** [comment]
I think it might be a problem related to java code
but I can't switch to kotlin on the project I am working on

**Comment by otopba** [comment]
@ahmed56734 Could you provide all source code of your sample app?

**Comment by ahmed56734** [comment]
> I think it might be a problem related to java code
> but I can't switch to kotlin on the project I am working on

I just called the code in the sample on a button tap

**Comment by otopba** [comment]
@ahmed56734 Hmm. I made the same flow, but everything work. I see `com.tafeel.masar_4_flutter` and `com.github.adee42.keyboardvisibility.KeyboardVisibilityPlugin`. Are you sure, thank you use only code from sample without any additional plugins or libraries ?

**Comment by ahmed56734** [comment]
made the same flow with java ?

**Comment by otopba** [comment]
> made the same flow with java ?

Yes, with java

**Comment by ahmed56734** [comment]
@otopba 
I added this dependency   flutter_typeahead: ^1.6.1
to your example app from here  https://github.com/vrtdev/flutter_workmanager/tree/master/example
and caused the same issue

**Comment by ahmed56734** [comment]
I am gonna lose my job for this

**Comment by timrijckaert** [comment]
Please this has been answered before. It is an issue with the `flutter_typeahead` plugin not properly implemented.

https://github.com/vrtdev/flutter_workmanager/issues/72#issuecomment-533411342

**Comment by winsonet** [comment]
I found that there's the same issue with [flutter_form_builder ](https://pub.dev/packages/flutter_form_builder)plugin :(

**Comment by ahmed56734** [comment]
![Screenshot from 2019-10-09 12-00-06](https://user-images.githubusercontent.com/10393214/66471901-7291f580-ea8c-11e9-9284-715a007d0c36.png)
flutter_form_builder depends on flutter_typeahed which depends on keyboard_visibility which causes the error
