### ISSUE TITLE
iOS build failure

### ISSUE THREAD

**Issue by raphaelakpan** [vrtdev/flutter_workmanager#86]
## Problem
I've gone through the setup instructions for Android and iOS. The Android app works great, however the iOS build keeps failing. I've spent a few days trying to fix this but not successful. Is there any reason my build would be failing with the output below?

## iOS Setup
- Plugin version => 0.1.1
- Xcode 9
- Swift 4.0 (as shown in `ios/Runner.xcodeproj/project.pbxproj`)

## Console build output
![image](https://user-images.githubusercontent.com/23452546/66039601-40711880-e50d-11e9-9669-431259cd5bcc.png)

_PS_: I get the same errors while trying to build the example app.

**Comment by Kymer** [comment]
Is there a specific reason you are using Xcode 9 and Swift 4.0?

The example app is currently setup to use Swift 4.2, see podfile:

`config.build_settings[‘SWIFT_VERSION’] = ‘4.2’`

**Comment by raphaelakpan** [comment]
That's the current Xcode and Swift setup I have on my machine. Upgrading would require upgrade my mac OS too. I guess that looks like the next steps to take.

**Comment by Kymer** [comment]
Maintaining Swift versions older than 4.2 is not really feasible for us, but we should be more clear about that in our iOS documentation 👍

**Comment by raphaelakpan** [comment]
Thanks for your response, appreciate. Will close this issue and comment in the future when I get it working.
