### ISSUE TITLE
there is no ^0.1.2 version

### ISSUE THREAD

**Issue by winsonet** [vrtdev/flutter_workmanager#87]
I just can get the lastest version from flutter pub with ^0.1.1, so I also can't use the new `executeTask` method, because the paramater is difference :(

just got below error when get the package:
~~~
depends on workmanager ^0.1.2 which doesn't match any versions, version solving failed.
~~~

**Comment by timrijckaert** [comment]
It was not released yet. But I'll do it now ;)
