### ISSUE TITLE
How can I pass data to callbackDispatcher in iOS?

### ISSUE THREAD

**Issue by winsonet** [vrtdev/flutter_workmanager#92]
for my case, I want to execute the background task after user login, so I need to get the user id or token in workmanager, I can just pass these in Android by `registerPeriodicTask` method, but there is no way for passing data in iOS, right?

**Comment by timrijckaert** [comment]
That's right.  
This is limited by the native iOS API we are using.  
We are looking to improve on this in a future update.

Stay tuned.

**Comment by winsonet** [comment]
oh, I really hope you can do that, thanks a lot!
