### ISSUE TITLE
When should the task will run on iOS?

### ISSUE THREAD

**Issue by winsonet** [vrtdev/flutter_workmanager#96]
thanks for fixed the iOS bug before, but I have the same issue with @raphaelakpan before, how do I know when will trigger the task in iOS? for now, I just can tigger it by manual in Xcode for testing, but when I tried to run in flutter and wait for 30mins, that's nothing happen :(

I have set below 
```
UIApplication.shared.setMinimumBackgroundFetchInterval(TimeInterval(60*15))
```
but still not working

**Comment by timrijckaert** [comment]
Read the [iOS Setup](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md#enabling-background-fetch)

> This ensures that the task is ran at most every 15 minutes.
> 
> 📝 Note: this is a minimum time interval, there's no guarantee on how often this will be called.

We also wished we knew.  
Maybe one day we have a direct contact with Tim Apple, but until then no-one knows.

**Comment by raphaelakpan** [comment]
Thanks for your explanation @Kymer, really helpful.

**Comment by winsonet** [comment]
I see, thanks!!
